import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {chromium} from '@playwright/test';

test('WebGL and Canvas preserve texture orientation, alpha and inverse clipping',async()=>{
 const bundle=await build({stdin:{contents:`import {CharacterWebGL} from './src/shared/character-webgl';import {drawCharacter} from './src/shared/character-canvas';import {characterSchema,characterInstanceSchema} from './src/shared/character-schema';
 window.probe=async()=>{const art=document.createElement('canvas');art.width=art.height=64;const ctx=art.getContext('2d');ctx.fillStyle='red';ctx.fillRect(8,8,24,24);ctx.fillStyle='blue';ctx.fillRect(32,32,24,24);const image=new Image();image.src=art.toDataURL();await image.decode();const images=new Map([['image',image]]),result=[];
 for(const inverse of [false,true])for(const gpu of [false,true]){const c=characterSchema.parse({id:'rig',name:'Rig',width:64,height:64,skins:[],clips:[],bones:[{id:'root',name:'Root'}],slots:[{id:'mask',name:'Mask',boneId:'root',attachmentId:'clip'},{id:'art',name:'Art',boneId:'root',attachmentId:'image'}],attachments:[{id:'clip',name:'Clip',slotId:'mask',kind:'clipping',width:64,height:64,points:[[0,0],[32,0],[32,64],[0,64]],inverse,clipEndSlotId:'art',pivot:[0,0]},{id:'image',name:'Image',slotId:'art',kind:'region',assetId:'image',width:64,height:64,pivot:[0,0]}]});const i=characterInstanceSchema.parse({characterId:'rig'}),canvas=document.createElement('canvas');canvas.width=canvas.height=64;document.body.append(canvas);let renderer;if(gpu){renderer=new CharacterWebGL(canvas);renderer.render(c,i,images,0);}else drawCharacter(canvas.getContext('2d'),c,i,images,0);const read=document.createElement('canvas');read.width=read.height=64;const target=read.getContext('2d');target.drawImage(canvas,0,0);const pixels=[[16,16],[48,48],[2,2]].map(([x,y])=>Array.from(target.getImageData(x,y,1,1).data));result.push({inverse,gpu,pixels});renderer?.dispose();canvas.remove();}return result;};`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,format:'iife',platform:'browser'});
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.setContent('<!doctype html><body></body>');await page.addScriptTag({content:bundle.outputFiles[0].text});const results=await page.evaluate(()=> (window as any).probe());for(const result of results){assert.deepEqual(result.pixels[0],result.inverse?[0,0,0,0]:[255,0,0,255],JSON.stringify(result));assert.deepEqual(result.pixels[1],result.inverse?[0,0,255,255]:[0,0,0,0]);assert.deepEqual(result.pixels[2],[0,0,0,0]);}}finally{await browser.close();}
});
