import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('real editor stores smooth ink and layered paint, reloads them and excludes private paint tiles from publication', async ({ page, baseURL }, testInfo) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const headers = { Origin: baseURL! };
  const signup = await page.request.post('/api/auth/register', { headers, data: { email: `creative-${randomUUID()}@studio.test`, password: randomUUID() + randomUUID(), name: 'Creative acceptance' } }); expect(signup.status()).toBe(201);
  const created = await page.request.post('/api/projects', { headers, data: { kind: 'web', name: 'Creative acceptance' } }); expect(created.status()).toBe(201);
  const { project } = await created.json();
  await page.goto(`/?project=${project.id}`);
  await page.getByRole('checkbox', { name: 'Live', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Open creative board', exact: true }).click();
  const canvas = page.getByLabel('Drawing canvas', { exact: true }), box = await canvas.boundingBox(); expect(box).toBeTruthy();
  await page.mouse.move(box!.x + box!.width * .2, box!.y + box!.height * .4); await page.mouse.down();
  for (let i = 0; i < 30; i++) await page.mouse.move(box!.x + box!.width * (.2 + i * .015), box!.y + box!.height * (.4 + Math.sin(i / 5) * .07));
  await page.mouse.up();
  await expect(canvas.locator('[data-board-element] path')).toHaveCount(1);
  await page.getByRole('button', { name: 'Undo board edit' }).click(); await expect(canvas.locator('[data-board-element] path')).toHaveCount(0);
  await page.getByRole('button', { name: 'Redo board edit' }).click(); await expect(canvas.locator('[data-board-element] path')).toHaveCount(1);
  await page.getByRole('button', { name: 'Text', exact: true }).click();
  await canvas.click({ position: { x: Math.round(box!.width * .45), y: Math.round(box!.height * .45) } });
  const boardText = page.getByRole('textbox', { name: 'Board text' });
  await boardText.press('ControlOrMeta+A');
  await boardText.pressSequentially('Smooth label');
  await page.getByRole('button', { name: 'Draw' }).click();
  await expect(canvas.locator('[data-board-element] text')).toContainText('Smooth label');
  await page.getByRole('button', { name: 'Undo board edit' }).click();
  await expect(canvas.locator('[data-board-element] text')).toContainText('Text');
  await page.getByRole('button', { name: 'Close creative board' }).click();
  await page.getByRole('button', { name: 'Open painting studio', exact: true }).click();
  await expect(page.getByLabel('Painting canvas', { exact: true })).toHaveAttribute('aria-busy', 'false');
  const paint = page.getByLabel('Painting canvas', { exact: true }), rect = await paint.boundingBox(); expect(rect).toBeTruthy();
  await page.mouse.move(rect!.x + rect!.width * .2, rect!.y + rect!.height * .4); await page.mouse.down();
  for (let i = 0; i < 20; i++) await page.mouse.move(rect!.x + rect!.width * (.2 + i * .025), rect!.y + rect!.height * (.4 + Math.sin(i / 4) * .05));
  const uploads = `**/api/projects/${project.id}/assets`;
  await page.route(uploads, route => route.abort('failed'));
  await page.mouse.up();
  await expect(page.getByRole('button', { name: 'Retry changes' })).toBeEnabled();
  await expect(page.getByRole('dialog', { name: 'Painting studio' }).getByRole('status')).toContainText('Your local work is kept here');
  const backupReady = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download PNG backup' }).click();
  const backup = await backupReady; expect(backup.suggestedFilename()).toMatch(/local-backup\.png$/);
  await backup.saveAs(testInfo.outputPath('painting-recovery.png'));
  await page.unroute(uploads);
  await page.getByRole('button', { name: 'Retry changes' }).click();
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled({ timeout: 20000 });
  await expect.poll(() => paint.evaluate((c: HTMLCanvasElement) => Array.from(c.getContext('2d')!.getImageData(0, 0, 512, 512).data).some((n, i) => i % 4 === 3 && n > 0))).toBe(true);
  await page.getByRole('button', { name: 'Add paint layer' }).click();
  await expect(page.getByRole('button', { name: 'Layer 2', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Layer 2', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled();
  await page.getByLabel('Layer blend', { exact: true }).selectOption('multiply');
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled();
  await page.getByLabel('Paint brush', { exact: true }).selectOption('smudge');
  const upperRect = (await paint.boundingBox())!;
  await page.mouse.move(upperRect.x + upperRect.width * .2, upperRect.y + upperRect.height * .4); await page.mouse.down();
  await page.mouse.move(upperRect.x + upperRect.width * .7, upperRect.y + upperRect.height * .4, { steps: 20 }); await page.mouse.up();
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath('painting-editor.png') });
  await page.getByRole('button', { name: 'Close painting studio' }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect.poll(async () => (await (await page.request.get(`/api/projects/${project.id}`)).json()).project.document.schemaVersion).toBe(2);
  const stored = (await (await page.request.get(`/api/projects/${project.id}`)).json()).project;
  expect(stored.document.boards[0].elements[0].points.length).toBeGreaterThan(10);
  expect(stored.document.paintings[0].layers[0].tiles.length).toBeGreaterThan(0);
  expect(stored.document.paintings[0].layers[1].tiles.length).toBeGreaterThan(0);
  expect(stored.document.paintings[0].layers[1].blend).toBe('multiply');
  expect(stored.document.paintings[0].composite.generation).toBe(stored.document.paintings[0].generation);
  await page.reload(); await page.getByRole('button', { name: 'Open painting studio', exact: true }).click();
  await expect.poll(() => page.getByLabel('Painting canvas', { exact: true }).evaluate((c: HTMLCanvasElement) => Array.from(c.getContext('2d')!.getImageData(0, 0, 512, 512).data).some((n, i) => i % 4 === 3 && n > 0))).toBe(true);
  const publication = await page.request.post(`/api/projects/${project.id}/publish`, { headers, data: {} }); expect(publication.status()).toBe(200);
  const { url } = await publication.json(), html = await (await page.request.get(url)).text();
  const tileId = stored.document.paintings[0].layers[0].tiles[0].assetId;
  expect(html).not.toContain(tileId);
  const hidden = await page.request.get(`${url}/assets/${tileId}`); expect(hidden.status()).toBe(404);
  expect(errors).toEqual([]);
});

test('a live response arriving inside painting waits, then preserves both the stroke and remote edits', async ({ page, baseURL }) => {
  const headers = { Origin: baseURL! };
  const signup = await page.request.post('/api/auth/register', { headers, data: { email: `live-paint-${randomUUID()}@studio.test`, password: randomUUID() + randomUUID() } });
  expect(signup.status()).toBe(201);
  const created = await page.request.post('/api/projects', { headers, data: { kind: 'web', name: 'Local painting' } });
  expect(created.status()).toBe(201);
  const { project } = await created.json();
  let release!: () => void, started!: () => void, requests = 0;
  const gate = new Promise<void>(resolve => { release = resolve; }), observed = new Promise<void>(resolve => { started = resolve; });
  await page.route(`**/api/projects/${project.id}/changes?*`, async route => {
    requests++; if (requests === 1) { started(); await gate; } await route.continue();
  });
  await page.goto(`/?project=${project.id}`);
  await observed;
  await page.getByRole('button', { name: 'Open painting studio', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled();
  const remote = structuredClone(project.document); remote.name = 'Remote rename';
  const saved = await page.request.put(`/api/projects/${project.id}/document`, { headers, data: { document: remote, expectedRevision: project.revision } }); expect(saved.status()).toBe(200);
  const response = page.waitForResponse(r => r.url().includes(`/api/projects/${project.id}/changes?`));
  release(); await response;
  const canvas = page.getByLabel('Painting canvas', { exact: true }), rect = (await canvas.boundingBox())!;
  await page.mouse.move(rect.x + rect.width * .2, rect.y + rect.height * .5); await page.mouse.down();
  await page.mouse.move(rect.x + rect.width * .7, rect.y + rect.height * .5, { steps: 20 }); await page.mouse.up();
  await expect(page.getByRole('button', { name: 'Close painting studio' })).toBeEnabled();
  expect(requests).toBe(1);
  await expect(page.getByRole('button', { name: 'Retry changes' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Close painting studio' }).click();
  await expect(page.getByRole('textbox', { name: 'Project name' })).toHaveValue('Remote rename');
  await expect.poll(async () => {
    const current = (await (await page.request.get(`/api/projects/${project.id}`)).json()).project.document;
    return current.name === 'Remote rename' && current.paintings?.[0]?.layers[0]?.tiles.length > 0;
  }).toBe(true);
});
