import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createDocument } from '../src/shared/catalog';
import { upgradeDocument } from '../src/shared/document-upgrade';
import { applyPaintingLayerOperation, paintingLayerOperationSchema } from '../src/shared/painting-layer-operations';
function fixture() { const doc=upgradeDocument(createDocument('slides')); doc.paintings.push({id:'paint',name:'Paint',width:512,height:512,generation:0,colorSpace:'srgb',algorithm:'cpu-srgb-grain-v1',tileSize:512,groups:[],layers:[{id:'a',name:'Layer',tiles:[],visible:true,locked:false,opacity:1,blend:'normal',alphaLock:false,clipping:false}]});return doc; }
function apply(doc: ReturnType<typeof fixture>, action: Record<string,unknown>) {return upgradeDocument(applyPaintingLayerOperation(doc,paintingLayerOperationSchema.parse({paintingId:'paint',expectedGeneration:doc.paintings[0].generation,...action})));}
test('layer commands increment generation, invalidate preview and preserve caller',()=>{const doc=fixture();const next=apply(doc,{op:'painting-layer-create',layerId:'b',name:'Upper'});assert.equal(doc.paintings[0].layers.length,1);assert.equal(next.paintings[0].generation,1);assert.equal(next.paintings[0].layers.length,2);assert.throws(()=>apply(next,{op:'painting-layer-update',layerId:'b',expectedGeneration:0,changes:{opacity:.5}}),/conflict/);});
test('group lock cannot be bypassed by moving or deleting a child',()=>{let doc=apply(fixture(),{op:'painting-group-create',groupId:'g'});doc=apply(doc,{op:'painting-layer-update',layerId:'a',changes:{groupId:'g'}});doc=apply(doc,{op:'painting-group-update',groupId:'g',changes:{locked:true}});assert.throws(()=>apply(doc,{op:'painting-layer-update',layerId:'a',changes:{groupId:null}}),/Unlock/);assert.throws(()=>apply(doc,{op:'painting-group-remove',groupId:'g'}),/Unlock/);assert.throws(()=>apply(doc,{op:'painting-layer-create',layerId:'b',groupId:'g'}),/Unlock/);});
test('group reordering moves real layer contributors and ungrouping keeps art',()=>{let doc=apply(fixture(),{op:'painting-group-create',groupId:'g1'});doc=apply(doc,{op:'painting-group-create',groupId:'g2'});doc=apply(doc,{op:'painting-layer-update',layerId:'a',changes:{groupId:'g1'}});doc=apply(doc,{op:'painting-layer-create',layerId:'b',groupId:'g2'});doc=apply(doc,{op:'painting-group-reorder',groupId:'g1',index:1});assert.deepEqual(doc.paintings[0].layers.map(l=>l.id),['b','a']);doc=apply(doc,{op:'painting-group-remove',groupId:'g1'});assert.equal(doc.paintings[0].layers.length,2);assert.equal(doc.paintings[0].layers[1].groupId,undefined);});
test('rejects duplicate groups, missing memberships and last-layer deletion',()=>{const doc=fixture();assert.throws(()=>apply(doc,{op:'painting-layer-update',layerId:'a',changes:{groupId:'missing'}}),/Unknown/);assert.throws(()=>apply(doc,{op:'painting-layer-remove',layerId:'a'}),/at least one/);const grouped=apply(doc,{op:'painting-group-create',groupId:'g'});assert.throws(()=>apply(grouped,{op:'painting-group-create',groupId:'g'}),/already exists/);});
