import { test, expect } from './authenticated-browser';
import { createDocument } from '../src/shared/catalog';
import type { Project } from '../src/shared/schema';
test('3D authoring persists a rig, rejects stale writes, previews without writes and exports GLB',async({page,baseURL})=>{
  const headers={Origin:baseURL!},doc=createDocument('3d','Character acceptance');doc.pages[0].nodes=[{id:'body',name:'Puppy body',type:'model3d',x:0,y:0,width:400,height:400,data:{geometry:'sphere'},scene:{position:[0,0,0],scale:[1,1,1]}}];
  const created=await page.request.post('/api/projects',{headers,data:{name:doc.name,kind:'3d',document:doc}});expect(created.status()).toBe(201);const project=(await created.json()).project as Project,path=`/api/projects/${project.id}`,pageId=project.document.pages[0].id;
  try{
    const invalid=await page.request.post(path+'/scene',{headers,data:{expectedRevision:project.revision,pageId,command:{action:'convert',nodeId:'missing'}}});expect(invalid.status()).toBe(400);
    const preview=await page.request.post(path+'/scene',{headers,data:{expectedRevision:project.revision,pageId,command:{action:'convert',nodeId:'body'}}});expect(preview.status()).toBe(200);expect((await preview.json()).preview).toBe(true);expect((await (await page.request.get(path)).json()).project.revision).toBe(project.revision);
    await page.goto(`/?project=${project.id}`);if(await page.locator('.mobile-editor-nav').isVisible())await page.locator('.mobile-editor-nav').getByRole('button',{name:'Canvas',exact:true}).click();await page.getByRole('checkbox',{name:'Live',exact:true}).uncheck();
    await page.getByRole('button',{name:'Character authoring',exact:true}).click();await expect(page.getByRole('region',{name:'3D character authoring'})).toBeVisible();
    // Selection is deterministic through the layer tree at both viewport sizes.
    if(await page.locator('.mobile-editor-nav').isVisible())await page.locator('.mobile-editor-nav').getByRole('button',{name:'Chat & layers',exact:true}).click();
    await page.getByRole('button',{name:'Layers',exact:true}).click();await page.getByRole('tree',{name:'Layers'}).getByRole('button',{name:'Puppy body',exact:true}).click();
    if(await page.locator('.mobile-editor-nav').isVisible())await page.locator('.mobile-editor-nav').getByRole('button',{name:'Canvas',exact:true}).click();
    const panel=page.getByRole('region',{name:'3D character authoring'});await panel.getByText('Surface & topology',{exact:true}).click();await panel.getByRole('button',{name:'Convert selected primitive',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);await expect(panel.getByRole('status')).toContainText('Applied');
    await panel.getByRole('button',{name:'Create quadruped rig',exact:true}).click();await expect(panel.getByRole('button',{name:'Auto-bind weights',exact:true})).toBeEnabled();await panel.getByRole('button',{name:'Auto-bind weights',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);await expect(panel.getByRole('status')).toContainText('Applied');
    await panel.getByText('Motion & expression',{exact:true}).click();await panel.getByRole('button',{name:'Add idle clip',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);await expect(panel.getByRole('status')).toContainText('Applied');await panel.getByRole('button',{name:'Inspect mesh & rig',exact:true}).click();await expect(panel.getByRole('status')).toContainText('vertices');
    await panel.getByRole('combobox',{name:'Motion clip',exact:true}).selectOption('idle-0');
    await panel.getByRole('spinbutton',{name:'Clip speed',exact:true}).fill('2');await panel.getByRole('spinbutton',{name:'Clip loops',exact:true}).fill('2');
    await panel.getByRole('slider',{name:'Clip amplitude',exact:true}).focus();await page.keyboard.press('Home');for(let i=0;i<10;i++)await page.keyboard.press('ArrowRight');
    await panel.getByRole('button',{name:'Apply clip settings',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);
    await panel.getByText('Viewport rig & brushes',{exact:true}).click();await panel.getByRole('button',{name:'Save mesh checkpoint',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);
    await panel.getByText('UV seams & material layers',{exact:true}).click();await panel.getByLabel('Name',{exact:true}).fill('Normal detail');await panel.getByRole('combobox',{name:'Map',exact:true}).selectOption('normal');await panel.getByRole('button',{name:'Save layer settings',exact:true}).click();await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);
    await panel.getByRole('button',{name:'Layer UV paint',exact:true}).focus();await page.keyboard.press('Enter');await expect(panel.getByText('Processing geometry…',{exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:'Save',exact:true})).toBeDisabled();await expect.poll(async()=>(await (await page.request.get(path)).json()).project.revision).toBe(project.revision+1);const saved=(await (await page.request.get(path)).json()).project as Project;expect(saved.document.pages[0].nodes[0].scene?.bones?.length).toBeGreaterThan(15);expect(saved.document.timeline?.tracks.length).toBe(1);expect(saved.document.pages[0].nodes[0].scene?.clips?.[0].amplitude).toBe(.5);expect(saved.document.pages[0].nodes[0].scene?.material?.layers?.[0].strokes.length).toBe(1);expect(saved.document.pages[0].nodes.some(n=>n.data?.checkpointOf==='body')).toBe(true);
    const stale=await page.request.post(path+'/scene',{headers,data:{pageId,expectedRevision:project.revision,preview:false,command:{action:'pose',nodeId:'body',bone:'head',rotation:[0,20,0]}}});expect(stale.status()).toBe(409);
    const read=await page.request.get(path+'/scene?time=0.5');expect(read.status()).toBe(200);expect((await read.json()).pages[0].nodes[0].skinned).toBe(true);
    const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export GLB',exact:true}).click();const file=await download;const stream=await file.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(chunk);const bytes=Buffer.concat(chunks);expect(bytes.toString('ascii',0,4)).toBe('glTF');const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());expect(json.skins[0].joints.length).toBeGreaterThan(15);expect(json.animations.length).toBeGreaterThan(0);expect(json.materials.some((m:any)=>m.normalTexture)).toBe(true);
    await page.reload();await expect(page.getByRole('button',{name:'Back to workspace'})).toBeVisible();
  }finally{await page.request.delete(path,{headers});}
});
