import type { Bindings } from './types';
import { communityReportSchema, communityResolveSchema, communityCollectionSchema, type CommunityCollection } from '../src/shared/community';
import { communityListing, retainedCommunityVersion, serializeCommunityFile, type CommunityFileRow } from './community-queries';
import { fail, id, hash, now } from './security';
interface ReportRow {id:string;listing_id:string;version:number;version_checksum:string;user_id:string;operation_id:string;payload_hash:string;reason:string;message:string;status:string;revision:number;created_at:string;updated_at:string;listing_revision?:number}
const serializeReport=(row:ReportRow)=>({id:row.id,listingId:row.listing_id,version:row.version,versionChecksum:row.version_checksum,reason:row.reason,message:row.message,status:row.status,revision:row.revision,createdAt:row.created_at,updatedAt:row.updated_at,listingRevision:row.listing_revision});
export async function reportCommunity(env:Bindings,userId:string,listingId:string,input:unknown) {const value=communityReportSchema.parse(input),payloadHash=await hash(JSON.stringify({listingId,...value})),existing=await env.DB.prepare('SELECT * FROM community_reports WHERE user_id=? AND operation_id=?').bind(userId,value.operationId).first<ReportRow>();if(existing){if(existing.payload_hash!==payloadHash)fail(409,'operation_conflict','This report operation ID belongs to a different request.');return serializeReport(existing);}const version=await retainedCommunityVersion(env,listingId,value.version),reportId=id(),time=now();await env.DB.prepare('INSERT INTO community_reports(id,listing_id,version,version_checksum,user_id,operation_id,payload_hash,reason,message,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,operation_id) DO NOTHING').bind(reportId,listingId,value.version,version.checksum,userId,value.operationId,payloadHash,value.reason,value.message,time,time).run();return serializeReport((await env.DB.prepare('SELECT * FROM community_reports WHERE user_id=? AND operation_id=?').bind(userId,value.operationId).first<ReportRow>())!);}
export async function communityReports(env:Bindings) {return (await env.DB.prepare('SELECT r.*,l.revision listing_revision FROM community_reports r JOIN community_listings l ON l.id=r.listing_id ORDER BY CASE r.status WHEN \'open\' THEN 0 ELSE 1 END,r.created_at DESC LIMIT 200').all<ReportRow>()).results.map(serializeReport);}
export async function communityReport(env:Bindings,reportId:string) {const row=await env.DB.prepare('SELECT r.*,l.revision listing_revision FROM community_reports r JOIN community_listings l ON l.id=r.listing_id WHERE r.id=?').bind(reportId).first<ReportRow>();if(!row)fail(404,'not_found','Report not found.');const available=!!await env.DB.prepare("SELECT 1 FROM community_versions v JOIN community_listings l ON l.id=v.listing_id WHERE v.listing_id=? AND v.version=? AND v.status='ready' AND l.deleted=0").bind(row!.listing_id,row!.version).first();const files=available?(await env.DB.prepare("SELECT * FROM community_files WHERE listing_id=? AND version=? AND status='ready' AND role='download'").bind(row!.listing_id,row!.version).all<CommunityFileRow>()).results.map(f=>({...serializeCommunityFile(f),url:`/api/community/moderation/reports/${reportId}/files/${f.id}`})):[];const history=(await env.DB.prepare('SELECT action,reason,created_at createdAt FROM community_moderation_actions WHERE report_id=? ORDER BY created_at').bind(reportId).all()).results;return {...serializeReport(row!),contentAvailable:available,previewUrl:available?`/api/community/moderation/reports/${reportId}/preview`:null,files,history};}
export async function resolveCommunityReport(env:Bindings,actorId:string,reportId:string,input:unknown) {
 const value=communityResolveSchema.parse(input),payloadHash=await hash(JSON.stringify({reportId,...value})),existing=await env.DB.prepare('SELECT payload_hash FROM community_moderation_actions WHERE actor_id=? AND operation_id=?').bind(actorId,value.operationId).first<{payload_hash:string}>();if(existing){if(existing.payload_hash!==payloadHash)fail(409,'operation_conflict','This operation ID belongs to a different moderation action.');return communityReport(env,reportId);}
 const report=await communityReport(env,reportId),time=now(),actionId=id();
 const results=await env.DB.batch([
 env.DB.prepare("UPDATE community_reports SET status='resolved',revision=revision+1,updated_at=? WHERE id=? AND revision=? AND EXISTS(SELECT 1 FROM community_listings WHERE id=community_reports.listing_id AND revision=?)").bind(time,reportId,value.expectedReportRevision,value.expectedListingRevision),
 env.DB.prepare('INSERT INTO community_moderation_actions(id,report_id,listing_id,actor_id,operation_id,payload_hash,action,reason,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(actionId,reportId,report.listingId,actorId,value.operationId,payloadHash,value.action,value.reason,time),
 ...(value.action==='dismiss'?[]:[env.DB.prepare(`UPDATE community_listings SET suppressed=?,moderation_reason=?,epoch=epoch+1,revision=revision+1,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM community_moderation_actions WHERE id=?)`).bind(value.action==='hide'?1:0,value.action==='hide'?value.reason:null,time,report.listingId,actionId)])
 ]);if(!(results[0] as {meta:{changes:number}}).meta.changes)fail(409,'revision_conflict','The report or listing changed. Reload before resolving.');return communityReport(env,reportId);
}
export async function communityCollections(env:Bindings,operator=false) {const rows=(await env.DB.prepare('SELECT * FROM community_collections ORDER BY updated_at DESC LIMIT 100').all<{id:string;title:string;description:string;revision:number}>()).results;const output:CommunityCollection[]=[];for(const row of rows){const items=(await env.DB.prepare('SELECT listing_id listingId,version,reason FROM community_collection_items WHERE collection_id=? ORDER BY position').bind(row.id).all<{listingId:string;version:number;reason:string}>()).results;const retained:CommunityCollection['items']=[];for(const item of items){try{const listing=await communityListing(env,item.listingId);if(listing.version===item.version)retained.push({...item,listing});else if(operator)retained.push(item);}catch(error){if(operator)retained.push(item);}}output.push({...row,items:retained});}return output;}
export async function saveCommunityCollection(env:Bindings,input:unknown,collectionId?:string) {const value=communityCollectionSchema.parse(input),time=now(),key=collectionId??id(),mutationToken=id();if(new Set(value.items.map(i=>i.listingId)).size!==value.items.length)fail(400,'duplicate_item','A collection can contain each design once.');for(const item of value.items){const listing=await communityListing(env,item.listingId);if(listing.version!==item.version)fail(409,'version_changed','Review the current design version before featuring it.');}
 const statements=[collectionId?env.DB.prepare('UPDATE community_collections SET title=?,description=?,revision=revision+1,updated_at=?,mutation_token=? WHERE id=? AND revision=?').bind(value.title,value.description,time,mutationToken,key,value.expectedCollectionRevision):env.DB.prepare('INSERT INTO community_collections(id,title,description,created_at,updated_at,mutation_token) SELECT ?,?,?,?,?,? WHERE ?=0').bind(key,value.title,value.description,time,time,mutationToken,value.expectedCollectionRevision)];
 // All item mutations require the unique successful claim, even for requests in the same millisecond.
 const revision=collectionId?value.expectedCollectionRevision+1:1;statements.push(env.DB.prepare('DELETE FROM community_collection_items WHERE collection_id=? AND EXISTS(SELECT 1 FROM community_collections WHERE id=? AND revision=? AND mutation_token=?)').bind(key,key,revision,mutationToken));
 for(let i=0;i<value.items.length;i++){const item=value.items[i];statements.push(env.DB.prepare('INSERT INTO community_collection_items(collection_id,listing_id,version,position,reason) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM community_collections WHERE id=? AND revision=? AND mutation_token=?) AND EXISTS(SELECT 1 FROM community_listings WHERE id=? AND current_version=? AND owner_available=1 AND suppressed=0 AND deleted=0)').bind(key,item.listingId,item.version,i,item.reason,key,revision,mutationToken,item.listingId,item.version));}
 const results=await env.DB.batch(statements);if(!(results[0] as {meta:{changes:number}}).meta.changes)fail(409,'revision_conflict','Collection changed. Reload before saving.');return (await communityCollections(env,true)).find(c=>c.id===key)!;
}
