import type { Bindings } from './types';
import { communityListing } from './community-queries';
import { communityProfile } from './community-profiles';
import { hash, now } from './security';
export async function bookmarkCommunity(env:Bindings,userId:string,listingId:string,saved:boolean) {if(saved){await communityListing(env,listingId);await env.DB.prepare('INSERT INTO community_bookmarks(user_id,listing_id,created_at) VALUES(?,?,?) ON CONFLICT(user_id,listing_id) DO NOTHING').bind(userId,listingId,now()).run();}else await env.DB.prepare('DELETE FROM community_bookmarks WHERE user_id=? AND listing_id=?').bind(userId,listingId).run();return {saved};}
export async function recordCommunityDelivery(env:Bindings,listingId:string,userId:string|null,network:string,action:'download'|'view') {
 const time=now(),day=time.slice(0,10),identity=await hash(`${day}:${userId?`user:${userId}`:`network:${network}`}`),column=action==='download'?'downloads_served':'views';
 const statements=[env.DB.prepare('INSERT INTO community_delivery_receipts(listing_id,day,identity_hash,action) VALUES(?,?,?,?) ON CONFLICT(listing_id,day,identity_hash,action) DO NOTHING').bind(listingId,day,identity,action),env.DB.prepare(`INSERT INTO community_daily_stats(listing_id,day,${column}) SELECT ?,?,1 WHERE changes()=1 ON CONFLICT(listing_id,day) DO UPDATE SET ${column}=${column}+1`).bind(listingId,day)];
 if(action==='download'&&userId)statements.push(env.DB.prepare("INSERT INTO community_contributions(listing_id,actor_id,action,first_at,last_at) SELECT ?,?,'download',?,? WHERE EXISTS(SELECT 1 FROM community_listings WHERE id=? AND user_id!=? AND owner_available=1 AND suppressed=0 AND deleted=0) ON CONFLICT(listing_id,actor_id,action) DO UPDATE SET last_at=excluded.last_at").bind(listingId,userId,time,time,listingId,userId));
 await env.DB.batch(statements);
}
export async function communityImpact(env:Bindings,userId:string) {const stats=await env.DB.prepare('SELECT COALESCE(SUM(s.views),0) views,COALESCE(SUM(s.downloads_served),0) downloadsServed FROM community_daily_stats s JOIN community_listings l ON l.id=s.listing_id WHERE l.user_id=?').bind(userId).first<{views:number;downloadsServed:number}>();const counts=await env.DB.prepare("SELECT COUNT(DISTINCT CASE c.action WHEN 'download' THEN c.actor_id END) uniqueDownloaders,COUNT(DISTINCT CASE c.action WHEN 'remix' THEN c.actor_id END) uniqueRemixers FROM community_contributions c JOIN community_listings l ON l.id=c.listing_id WHERE l.user_id=?").bind(userId).first<{uniqueDownloaders:number;uniqueRemixers:number}>();const designs=await env.DB.prepare('SELECT COUNT(*) n FROM community_listings WHERE user_id=? AND current_version IS NOT NULL').bind(userId).first<{n:number}>();return {...stats!,...counts!,publishedDesigns:designs!.n,badges:(await communityProfile(env,userId))?.badges??[],coverage:{views:'Approximate unique daily deliveries; last 30 days.',downloadsServed:'Capped daily delivery identities; last 30 days.',uniqueDownloaders:'Lifetime distinct other signed-in people served downloads.',uniqueRemixers:'Lifetime distinct other people with committed remixes.'}};}
