import { Hono } from 'hono';
import type { Env } from './types';
import { communityFormatSchema, communityIdSchema } from '../src/shared/community';
import { communityCategories, communityLicense } from '../src/shared/community-taxonomy';
import { communityEnabled, communityOperator, communityRateLimit, isCommunityOperator } from './community-access';
import { communityListing, listCommunity, ownedCommunityListings } from './community-queries';
import { communityProfile, saveCommunityProfile } from './community-profiles';
import { generateCommunityProfile } from './community-profile-generation';
import { generateCommunityMetadata } from './community-metadata-generation';
import { preflightCommunity, publishCommunity, unlistCommunity } from './community-publication';
import { communityJobReceipt, dispatchCommunityJob, serializeCommunityJob } from './community-jobs';
import { remixCommunity } from './community-remix';
import { importCommunity } from './community-import';
import { bookmarkCommunity, communityImpact, recordCommunityDelivery } from './community-engagement';
import { communityPreview, serveCommunityFile } from './community-downloads';
import { communityCollections, communityReport, communityReports, reportCommunity, resolveCommunityReport, saveCommunityCollection } from './community-moderation';
import { fail, owner, rateLimit } from './security';
export const communityRoutes=new Hono<Env>();
const communityVersion=(value:string)=>{const version=Number(value);if(!Number.isSafeInteger(version)||version<1)fail(400,'invalid_version','Version must be a positive integer.');return version;};
communityRoutes.use('*',async(c,next)=>{c.header('Cache-Control','private, no-store');const relative=c.req.path.replace(/^\/api\/community/,'');if(!communityEnabled(c.env)&&!/^\/(jobs|moderation)\//.test(relative))fail(503,'community_disabled','Community is not enabled on this deployment.');await next();});
communityRoutes.get('/taxonomy',c=>c.json({categories:communityCategories,formats:communityFormatSchema.options,license:communityLicense}));
communityRoutes.get('/listings',async c=>{await rateLimit(c,'community-public',120);return c.json(await listCommunity(c.env,c.req.query()));});
communityRoutes.get('/listings/:id',async c=>{const listing=await communityListing(c.env,c.req.param('id'));if(c.req.method!=='HEAD')await recordCommunityDelivery(c.env,listing.id,c.get('user')?.id??null,c.req.header('CF-Connecting-IP')??'local','view');return c.json({listing});});
communityRoutes.get('/listings/:id/versions/:version/preview',async c=>communityPreview(c,c.req.param('id'),communityVersion(c.req.param('version'))));
communityRoutes.get('/listings/:id/versions/:version/files/:fileId',async c=>serveCommunityFile(c,c.req.param('id'),communityVersion(c.req.param('version')),c.req.param('fileId')));
communityRoutes.get('/creators/:handle',async c=>{const row=await c.env.DB.prepare('SELECT user_id FROM community_profiles WHERE handle=?').bind(c.req.param('handle').toLowerCase()).first<{user_id:string}>();if(!row)fail(404,'not_found','Creator not found.');return c.json({profile:await communityProfile(c.env,row!.user_id),...await listCommunity(c.env,{...c.req.query(),creator:c.req.param('handle')})});});
communityRoutes.get('/collections',async c=>c.json({collections:await communityCollections(c.env)}));
communityRoutes.get('/collections/:id',async c=>{const collection=(await communityCollections(c.env)).find(item=>item.id===c.req.param('id'));if(!collection)fail(404,'not_found','Collection not found.');return c.json({collection});});
communityRoutes.get('/me/profile',async c=>c.json({profile:await communityProfile(c.env,owner(c)),moderator:await isCommunityOperator(c)}));
communityRoutes.put('/me/profile',async c=>c.json({profile:await saveCommunityProfile(c.env,owner(c),await c.req.json())}));
communityRoutes.post('/me/profile/generate',async c=>c.json(await generateCommunityProfile(c,await c.req.json())));
communityRoutes.post('/metadata/generate',async c=>c.json(await generateCommunityMetadata(c,await c.req.json())));
communityRoutes.get('/me/listings',async c=>c.json({listings:await ownedCommunityListings(c.env,owner(c))}));
communityRoutes.get('/me/bookmarks',async c=>c.json({listings:await ownedCommunityListings(c.env,owner(c),true)}));
communityRoutes.get('/me/impact',async c=>c.json({impact:await communityImpact(c.env,owner(c))}));
communityRoutes.post('/preflight',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'preflight',60);return c.json({preflight:await preflightCommunity(c.env,userId,await c.req.json())});});
communityRoutes.post('/listings',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'publish');return c.json({job:await publishCommunity(c.env,userId,await c.req.json())},202);});
communityRoutes.post('/listings/:id/releases',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'publish');return c.json({job:await publishCommunity(c.env,userId,await c.req.json(),c.req.param('id'))},202);});
communityRoutes.post('/listings/:id/unlist',async c=>c.json({job:await unlistCommunity(c.env,owner(c),c.req.param('id'),await c.req.json())}));
communityRoutes.get('/jobs/:operationId',async c=>{const row=await communityJobReceipt(c.env,owner(c),c.req.param('operationId'));if(!row)fail(404,'not_found','Operation not found.');if(row!.status==='queued')await dispatchCommunityJob(c.env,row!.id);return c.json({job:serializeCommunityJob(row!)});});
communityRoutes.get('/jobs/:operationId/preview',async c=>{const row=await communityJobReceipt(c.env,owner(c),c.req.param('operationId'));if(row?.kind!=='publish'||!row.listing_id||!row.version)fail(404,'not_found','Operation preview not found.');return communityPreview(c,row!.listing_id!,row!.version!,row!.id);});
communityRoutes.get('/jobs/:operationId/files/:fileId',async c=>{const row=await communityJobReceipt(c.env,owner(c),c.req.param('operationId'));if(!row)fail(404,'not_found','Operation not found.');return serveCommunityFile(c,row!.listing_id??'',row!.version??0,c.req.param('fileId'),row!.id);});
communityRoutes.post('/listings/:id/remix',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'remix');return c.json({job:await remixCommunity(c.env,userId,c.req.param('id'),await c.req.json())},202);});
communityRoutes.post('/imports',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'import');const body=await c.req.parseBody(),file=body.file;if(!(file instanceof File)||typeof body.operationId!=='string')fail(400,'invalid_import','Provide a Studio ZIP file and operationId.');return c.json({job:await importCommunity(c.env,userId,body.operationId as string,new Uint8Array(await (file as File).arrayBuffer()))},202);});
communityRoutes.put('/listings/:id/bookmark',async c=>c.json(await bookmarkCommunity(c.env,owner(c),c.req.param('id'),true)));
communityRoutes.delete('/listings/:id/bookmark',async c=>c.json(await bookmarkCommunity(c.env,owner(c),c.req.param('id'),false)));
communityRoutes.post('/listings/:id/reports',async c=>{const userId=owner(c);await communityRateLimit(c.env,userId,'report',10);return c.json({report:await reportCommunity(c.env,userId,c.req.param('id'),await c.req.json())},201);});
communityRoutes.use('/moderation/*',async(c,next)=>{await communityOperator(c);await next();});
communityRoutes.get('/moderation/reports',async c=>c.json({reports:await communityReports(c.env)}));
communityRoutes.get('/moderation/reports/:id',async c=>c.json({report:await communityReport(c.env,c.req.param('id'))}));
communityRoutes.get('/moderation/reports/:id/preview',async c=>{const report=await communityReport(c.env,c.req.param('id'));if(!report.contentAvailable)fail(404,'content_unavailable','The reported version has been purged.');return communityPreview(c,report.listingId,report.version,undefined,true);});
communityRoutes.get('/moderation/reports/:id/files/:fileId',async c=>{const report=await communityReport(c.env,c.req.param('id'));if(!report.contentAvailable)fail(404,'content_unavailable','The reported version has been purged.');return serveCommunityFile(c,report.listingId,report.version,c.req.param('fileId'),undefined,true);});
communityRoutes.post('/moderation/reports/:id/resolve',async c=>c.json({report:await resolveCommunityReport(c.env,await communityOperator(c),c.req.param('id'),await c.req.json())}));
communityRoutes.post('/moderation/collections',async c=>c.json({collection:await saveCommunityCollection(c.env,await c.req.json())},201));
communityRoutes.get('/moderation/collections',async c=>c.json({collections:await communityCollections(c.env,true)}));
communityRoutes.put('/moderation/collections/:id',async c=>c.json({collection:await saveCommunityCollection(c.env,await c.req.json(),c.req.param('id'))}));
