import type { Bindings } from './types';
import { documentSchema, type DesignDocument, type AssetRef } from '../src/shared/schema';
import { remapDocumentAssets } from '../src/shared/document-asset-references';
import { buildCommunityPackage, readCommunityPackage } from '../src/shared/community-package';
import type { CommunityAttribution } from '../src/shared/community';
import { renderCommunitySnapshot } from './snapshot-export';
import { assertCommunityLease, communityChecksum, purgeCommunityFiles, reconcileCommunityWrites, reserveCommunityStorage, writeCommunityFile } from './community-assets';
import type { CommunityJobRow } from './community-jobs';
import type { CommunityFileRow } from './community-queries';
import type { PublicationInput } from './community-publication';
import { ApiError, fail, id, now } from './security';
import { communityMilestones } from '../src/shared/community-taxonomy';
import { communityEnabled } from './community-access';
const textBytes=(text:string)=>new TextEncoder().encode(text);
async function updateStage(env:Bindings,job:CommunityJobRow,lease:string,stage:string) {await assertCommunityLease(env,job.id,lease);await env.DB.prepare("UPDATE community_jobs SET stage=?,updated_at=? WHERE id=? AND lease=? AND status='running'").bind(stage,now(),job.id,lease).run();}
async function existingFile(env:Bindings,jobId:string,fileId:string,lease:string) {await assertCommunityLease(env,jobId,lease);const row=await env.DB.prepare("SELECT * FROM community_files WHERE job_id=? AND id=? AND status='ready'").bind(jobId,fileId).first<CommunityFileRow>();if(!row)return null;const object=await env.ASSETS_BUCKET.get(row.storage_key);if(!object)fail(409,'artifact_unavailable','A committed artifact is missing.');const bytes=new Uint8Array(await object!.arrayBuffer());if(await communityChecksum(bytes)!==row.checksum)fail(409,'artifact_corrupt','Stored artifact checksum does not match.');await assertCommunityLease(env,jobId,lease);return {row,bytes};}
async function checkedRead(env:Bindings,job:CommunityJobRow,lease:string,key:string) {await assertCommunityLease(env,job.id,lease);const object=await env.ASSETS_BUCKET.get(key);if(!object)fail(404,'asset_unavailable','A required asset is unavailable.');const bytes=new Uint8Array(await object!.arrayBuffer());await assertCommunityLease(env,job.id,lease);return bytes;}
async function processPublish(env:Bindings,job:CommunityJobRow,lease:string) {
 const input=JSON.parse(job.input) as PublicationInput,doc=structuredClone(input.document),mapping=new Map<string,AssetRef>();
 const packageAssets:{id:string;name:string;mimeType:string;bytes:Uint8Array}[]=[];
 await updateStage(env,job,lease,'copying-assets');
 for(let i=0;i<input.assetSources.length;i++){const source=input.assetSources[i],fileId=`${job.id}_asset_${i}`,cached=await existingFile(env,job.id,fileId,lease),bytes=cached?.bytes??await checkedRead(env,job,lease,source.storageKey);
  const file=cached?.row??await writeCommunityFile(env,{jobId:job.id,userId:job.user_id,listingId:job.listing_id,version:job.version,lease,fileId,role:'asset',filename:`media-${i+1}`,mimeType:source.mimeType,bytes});
  mapping.set(source.id,{id:fileId,name:`Media ${i+1}`,type:source.mimeType.split('/')[0],mimeType:source.mimeType,url:`/api/assets/${fileId}`,size:bytes.byteLength});packageAssets.push({id:fileId,name:`Media ${i+1}`,mimeType:source.mimeType,bytes});
 }
 remapDocumentAssets(doc,mapping);const projected=documentSchema.parse(doc);
 await assertCommunityLease(env,job.id,lease);
 await env.DB.prepare("UPDATE community_versions SET document=? WHERE listing_id=? AND version=? AND status='building' AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND lease=? AND status='running' AND lease_until>?)").bind(JSON.stringify(projected),job.listing_id,job.version,job.id,lease,Date.now()).run();
 const resolver=async(url:string)=>{const asset=packageAssets.find(a=>url===`/api/assets/${a.id}`);if(!asset)fail(400,'invalid_asset','The renderer requested a file outside this Community version.');return {bytes:asset!.bytes,mimeType:asset!.mimeType};};
 await updateStage(env,job,lease,'rendering-cover');
 const coverId=`${job.id}_cover`;if(!await existingFile(env,job.id,coverId,lease)){const cover=await renderCommunitySnapshot(env,projected,{format:'png',pageIndex:input.metadata.cover.pageIndex,start:input.metadata.cover.time??0},resolver,true,input.metadata.cover);await assertCommunityLease(env,job.id,lease);await writeCommunityFile(env,{jobId:job.id,userId:job.user_id,listingId:job.listing_id,version:job.version,lease,fileId:coverId,role:'cover',filename:'cover.png',mimeType:cover.mimeType,bytes:cover.bytes});}
 await updateStage(env,job,lease,'rendering-formats');
 for(let i=0;i<input.metadata.formats.length;i++){const options=input.metadata.formats[i],fileId=`${job.id}_export_${i}`;if(await existingFile(env,job.id,fileId,lease))continue;const artifact=await renderCommunitySnapshot(env,projected,options,resolver);await assertCommunityLease(env,job.id,lease);await writeCommunityFile(env,{jobId:job.id,userId:job.user_id,listingId:job.listing_id,version:job.version,lease,fileId,role:'download',format:options.format,options,filename:`${i+1}-${artifact.filename}`,mimeType:artifact.mimeType,bytes:artifact.bytes});}
 await updateStage(env,job,lease,'packaging');
 const packageId=`${job.id}_package`,attribution:CommunityAttribution={listingId:job.listing_id!,version:job.version!,title:input.metadata.title,creator:input.creator,license:'CC-BY-4.0',...(env.APP_URL?.startsWith('https://')?{url:`${env.APP_URL}/community/designs/${job.listing_id}`} :{}),verified:true};
 if(!await existingFile(env,job.id,packageId,lease)){const bytes=await buildCommunityPackage(projected,packageAssets,attribution,job.id);await readCommunityPackage(bytes);await writeCommunityFile(env,{jobId:job.id,userId:job.user_id,listingId:job.listing_id,version:job.version,lease,fileId:packageId,role:'download',format:'package',filename:'studio-project.zip',mimeType:'application/zip',bytes});}
 await updateStage(env,job,lease,'activating');
 if(!communityEnabled(env))fail(503,'community_paused','Publication will resume when Community is enabled.');
 const time=now(),results=await env.DB.batch([
 env.DB.prepare(`UPDATE community_versions SET document=?,status='ready' WHERE listing_id=? AND version=? AND EXISTS(SELECT 1 FROM community_jobs j JOIN community_listings l ON l.id=j.listing_id WHERE j.id=? AND j.lease=? AND j.lease_until>? AND j.status='running' AND l.pending_job_id=j.id AND l.epoch=j.epoch AND l.suppressed=0 AND l.deleted=0 AND EXISTS(SELECT 1 FROM projects WHERE id=j.source_project_id) AND NOT EXISTS(SELECT 1 FROM community_source_locks WHERE project_id=j.source_project_id AND deleting=1)) AND (SELECT COUNT(*) FROM community_files WHERE job_id=? AND status='ready')=?`).bind(JSON.stringify(projected),job.listing_id,job.version,job.id,lease,Date.now(),job.id,input.assetSources.length+input.metadata.formats.length+2),
 env.DB.prepare('UPDATE community_listings SET current_version=?,owner_available=1,revision=revision+1,pending_job_id=NULL,first_published_at=COALESCE(first_published_at,?),updated_at=? WHERE id=? AND changes()=1').bind(job.version,time,time,job.listing_id),
 env.DB.prepare("UPDATE community_jobs SET status='succeeded',stage='completed',result=?,lease=NULL,lease_until=0,updated_at=? WHERE id=? AND lease=? AND changes()=1").bind(JSON.stringify({listingId:job.listing_id,version:job.version}),time,job.id,lease),
 env.DB.prepare("INSERT INTO community_badges(user_id,badge,awarded_at) SELECT ?,'first-publication',? WHERE EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded') ON CONFLICT(user_id,badge) DO NOTHING").bind(job.user_id,time,job.id),
 env.DB.prepare("DELETE FROM community_storage_reservations WHERE job_id=? AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded')").bind(job.id,job.id)
 ]);if(!(results[0] as {meta:{changes:number}}).meta.changes)fail(409,'publication_revoked','Publication was revoked or its required files are incomplete.');
}
export function independentCommunityDocument(source:DesignDocument,projectId:string) {
 const document=structuredClone(source),mapping=new Map<string,string>();
 for(const page of document.pages){mapping.set(page.id,id());for(const node of page.nodes)mapping.set(node.id,id());}
 for(const page of document.pages){page.id=mapping.get(page.id)!;for(const node of page.nodes){node.id=mapping.get(node.id)!;if(node.parentId)node.parentId=mapping.get(node.parentId)??node.parentId;for(const interaction of node.interactions??[])if(interaction.action!=='url')interaction.target=mapping.get(interaction.target)??interaction.target;if(node.scene?.rigId)node.scene.rigId=mapping.get(node.scene.rigId)??node.scene.rigId;if(typeof node.data?.rigSourceId==='string')node.data.rigSourceId=mapping.get(node.data.rigSourceId)??node.data.rigSourceId;}}
 for(const track of document.timeline?.tracks??[]){track.id=id();track.nodeId=mapping.get(track.nodeId)??track.nodeId;}
 document.id=projectId;return document;
}
async function processCopy(env:Bindings,job:CommunityJobRow,lease:string) {
 const input=JSON.parse(job.input) as {projectId:string;document:DesignDocument;files:CommunityFileRow[];attribution:CommunityAttribution;inputFileId?:string};
 let source=input.document,attribution=input.attribution,assets:{id:string;name:string;mimeType:string;bytes:Uint8Array}[]=[];
 await updateStage(env,job,lease,'copying-assets');
 if(job.kind==='import'){const file=await env.DB.prepare("SELECT * FROM community_files WHERE id=? AND job_id=? AND role='input' AND status='ready'").bind(input.inputFileId,job.id).first<CommunityFileRow>();if(!file)fail(404,'package_unavailable','Import package is unavailable.');const parsed=await readCommunityPackage(await checkedRead(env,job,lease,file!.storage_key));source=parsed.document;attribution={...parsed.attribution,verified:false};assets=parsed.assets;
 }else{for(const file of input.files)assets.push({id:file.id,name:file.filename,mimeType:file.mime_type,bytes:await checkedRead(env,job,lease,file.storage_key)});}
 let doc=independentCommunityDocument(source,input.projectId);const mapping=new Map<string,AssetRef>(),written:CommunityFileRow[]=[];
 for(let i=0;i<assets.length;i++){const asset=assets[i],fileId=`${job.id}_owned_${i}`,file=await writeCommunityFile(env,{jobId:job.id,userId:job.user_id,lease,fileId,role:'asset',filename:`media-${i+1}`,mimeType:asset.mimeType,bytes:asset.bytes});written.push(file);mapping.set(asset.id,{id:fileId,name:`Media ${i+1}`,type:asset.mimeType.split('/')[0],mimeType:asset.mimeType,url:`/api/assets/${fileId}`,size:asset.bytes.byteLength});}
 remapDocumentAssets(doc,mapping);doc.metadata={createdAt:now(),updatedAt:now()};doc=documentSchema.parse(doc);
 await updateStage(env,job,lease,'committing-project');
 const time=now(),sourceGuard=job.kind==='remix'?"AND EXISTS(SELECT 1 FROM community_listings l JOIN community_versions v ON v.listing_id=l.id WHERE l.id=j.listing_id AND l.epoch=j.epoch AND l.owner_available=1 AND l.suppressed=0 AND l.deleted=0 AND v.version=j.version AND v.status='ready')":'';
 const statements=[env.DB.prepare(`INSERT INTO projects(id,user_id,name,description,kind,document,revision,created_at,updated_at) SELECT ?,?,?,?,?,?,1,?,? WHERE EXISTS(SELECT 1 FROM community_jobs j WHERE j.id=? AND j.lease=? AND j.lease_until>? AND j.status='running' ${sourceGuard})`).bind(input.projectId,job.user_id,doc.name,'',doc.kind,JSON.stringify(doc),time,time,job.id,lease,Date.now()),
 env.DB.prepare("UPDATE community_jobs SET status='succeeded',stage='completed',result=?,lease=NULL,lease_until=0,updated_at=? WHERE id=? AND lease=? AND changes()=1").bind(JSON.stringify({projectId:input.projectId}),time,job.id,lease)];
 for(const file of written)statements.push(env.DB.prepare(`INSERT INTO assets(id,user_id,project_id,name,mime_type,size,storage_key,created_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded')`).bind(file.id,job.user_id,input.projectId,file.filename,file.mime_type,file.size,file.storage_key,time,job.id));
 statements.push(env.DB.prepare(`INSERT INTO community_remix_origins(project_id,listing_id,version,attribution,verified,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded')`).bind(input.projectId,job.kind==='remix'?job.listing_id:null,job.kind==='remix'?job.version:null,JSON.stringify(attribution),job.kind==='remix'?1:0,time,job.id));
 if(job.kind==='remix')statements.push(env.DB.prepare("INSERT INTO community_contributions(listing_id,actor_id,action,first_at,last_at) SELECT ?,?,'remix',?,? WHERE EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded') AND EXISTS(SELECT 1 FROM community_listings WHERE id=? AND user_id!=?) ON CONFLICT(listing_id,actor_id,action) DO NOTHING").bind(job.listing_id,job.user_id,time,time,job.id,job.listing_id,job.user_id));
 statements.push(env.DB.prepare("UPDATE community_files SET status='deleted' WHERE job_id=? AND role='asset' AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded')").bind(job.id,job.id),env.DB.prepare("DELETE FROM community_storage_reservations WHERE job_id=? AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='succeeded')").bind(job.id,job.id));
 const results=await env.DB.batch(statements);if(!(results[0] as {meta:{changes:number}}).meta.changes)fail(409,'source_revoked','The original design was revoked before this remix committed.');
 if(job.kind==='remix')for(const milestone of communityMilestones)await env.DB.prepare(`INSERT INTO community_badges(user_id,badge,awarded_at) SELECT l.user_id,?,? FROM community_listings l WHERE l.id=? AND (SELECT COUNT(DISTINCT c.actor_id) FROM community_contributions c JOIN community_listings own ON own.id=c.listing_id WHERE own.user_id=l.user_id AND c.action='remix')>=? ON CONFLICT(user_id,badge) DO NOTHING`).bind(`remixed-by-${milestone}`,time,job.listing_id,milestone).run();
}
export async function processCommunityJob(env:Bindings,jobId:string) {
 // Recover an admission interrupted between the durable source claim and quota reservation.
 const unreserved=await env.DB.prepare("SELECT * FROM community_jobs WHERE id=? AND status='queued' AND kind IN('publish','remix') AND NOT EXISTS(SELECT 1 FROM community_storage_reservations WHERE job_id=community_jobs.id)").bind(jobId).first<CommunityJobRow>();
 if(unreserved&&communityEnabled(env)){try{const input=JSON.parse(unreserved.input),bytes=unreserved.kind==='publish'?Math.min(512*1024**2,(input.assetSources as PublicationInput['assetSources']).reduce((sum,a)=>sum+a.size,0)*3+64*1024**2*(1+input.metadata.formats.length)):(input.files as CommunityFileRow[]).reduce((sum,f)=>sum+f.size,0);await reserveCommunityStorage(env,jobId,unreserved.user_id,bytes);}catch(error){await env.DB.prepare("UPDATE community_jobs SET status='failed',stage='failed',error=? WHERE id=? AND status='queued'").bind(JSON.stringify({code:'asset_quota_exceeded',message:'Storage admission could not be recovered. Start a new operation after freeing capacity.'}),jobId).run();}}
 const lease=id(),time=Date.now();const claim=await env.DB.prepare(`UPDATE community_jobs SET status='running',lease=?,lease_until=?,attempts=attempts+1,updated_at=? WHERE id=? AND stage!='receiving' AND (status='queued' OR (status='running' AND lease_until<=?)) AND (kind='cleanup' OR (?=1 AND EXISTS(SELECT 1 FROM community_storage_reservations WHERE job_id=community_jobs.id))) AND NOT EXISTS(SELECT 1 FROM community_source_locks WHERE project_id=community_jobs.source_project_id AND deleting=1)`).bind(lease,time+300000,now(),jobId,time,communityEnabled(env)?1:0).run();if(!claim.meta.changes){await reconcileCommunityStorage(env);const state=await env.DB.prepare('SELECT status FROM community_jobs WHERE id=?').bind(jobId).first<{status:string}>();return !state||['succeeded','failed'].includes(state.status);}
 const job=(await env.DB.prepare('SELECT * FROM community_jobs WHERE id=? AND lease=?').bind(jobId,lease).first<CommunityJobRow>())!;
 try{if(job.kind==='publish')await processPublish(env,job,lease);else if(job.kind==='remix'||job.kind==='import')await processCopy(env,job,lease);else if(job.kind==='cleanup'){
 await reconcileCommunityStorage(env);const pending=await env.DB.prepare("SELECT 1 FROM community_files WHERE listing_id=? AND status!='deleted' LIMIT 1").bind(job.listing_id).first();await env.DB.prepare("UPDATE community_jobs SET status=?,stage=?,lease=NULL,lease_until=0,updated_at=? WHERE id=? AND lease=?").bind(pending?'queued':'succeeded',pending?'cleaning':'completed',now(),jobId,lease).run();return !pending;
 }else fail(400,'invalid_job','Unknown Community operation.');}
 catch(error){if(error instanceof ApiError&&error.code==='lease_lost')return false;if(job.kind==='cleanup'||error instanceof ApiError&&error.code==='community_paused'){await env.DB.prepare("UPDATE community_jobs SET status='queued',stage=?,lease=NULL,lease_until=0,updated_at=? WHERE id=? AND lease=?").bind(job.kind==='cleanup'?'cleaning':'awaiting-enable',now(),jobId,lease).run();return false;}const detail=error instanceof ApiError?{code:error.code,message:error.message}:{code:'community_build_failed',message:error instanceof Error?error.message:'Community operation failed.'};await env.DB.batch([env.DB.prepare("UPDATE community_jobs SET status='failed',stage='failed',error=?,lease=NULL,lease_until=0,updated_at=? WHERE id=? AND lease=? AND status='running'").bind(JSON.stringify(detail),now(),jobId,lease),env.DB.prepare("UPDATE community_listings SET pending_job_id=NULL WHERE pending_job_id=? AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='failed')").bind(jobId,jobId),env.DB.prepare("UPDATE community_versions SET status='failed' WHERE listing_id=? AND version=? AND status='building' AND EXISTS(SELECT 1 FROM community_jobs WHERE id=? AND status='failed')").bind(job.listing_id,job.version,jobId)]);}
 await reconcileCommunityStorage(env);
 return true;
}
export async function reconcileCommunityStorage(env:Bindings) {
 await reconcileCommunityWrites(env);
 // Revoke old versions before deleting any bytes; readers can no longer start copying them.
 await env.DB.prepare(`UPDATE community_versions SET status='purging' WHERE status='ready' AND (EXISTS(SELECT 1 FROM community_listings l WHERE l.id=listing_id AND l.deleted=1) OR (SELECT COUNT(*) FROM community_versions v WHERE v.listing_id=community_versions.listing_id AND v.status='ready' AND v.version>community_versions.version)>=2) AND NOT EXISTS(SELECT 1 FROM community_jobs j WHERE j.listing_id=community_versions.listing_id AND j.version=community_versions.version AND j.status='running' AND j.lease_until>?)`).bind(Date.now()).run();
 await env.DB.prepare("UPDATE community_jobs SET status='failed',stage='failed',error=?,lease=NULL,lease_until=0 WHERE (status='queued' OR (status='running' AND lease_until<=?)) AND source_project_id IN(SELECT project_id FROM community_source_locks WHERE deleting=1)").bind(JSON.stringify({code:'source_deleted',message:'The source project was deleted.'}),Date.now()).run();
 await env.DB.prepare("UPDATE community_jobs SET status='failed',stage='failed',error=?,lease=NULL,lease_until=0 WHERE status='queued' AND stage='receiving' AND updated_at<?").bind(JSON.stringify({code:'import_upload_expired',message:'The import upload did not finish. Retry with a new operation ID.'}),new Date(Date.now()-3600000).toISOString()).run();
 await env.DB.prepare("UPDATE community_listings SET pending_job_id=NULL WHERE pending_job_id IN(SELECT id FROM community_jobs WHERE status='failed')").run();
 const files=(await env.DB.prepare(`SELECT f.* FROM community_files f JOIN community_jobs j ON j.id=f.job_id WHERE f.status!='deleted' AND ((j.status='failed' AND j.lease_until<=?) OR (j.status='succeeded' AND f.role='input') OR EXISTS(SELECT 1 FROM community_versions v WHERE v.listing_id=f.listing_id AND v.version=f.version AND v.status='purging')) LIMIT 100`).bind(Date.now()).all<CommunityFileRow>()).results;
 await purgeCommunityFiles(env,files);
 await env.DB.prepare("UPDATE community_versions SET status='purged',document='{}',disclosure='{}',metadata='{}' WHERE status='purging' AND NOT EXISTS(SELECT 1 FROM community_files f WHERE f.listing_id=community_versions.listing_id AND f.version=community_versions.version AND f.status!='deleted')").run();
 await env.DB.prepare("UPDATE community_jobs SET input='{}' WHERE kind='publish' AND status IN('failed','succeeded') AND EXISTS(SELECT 1 FROM community_listings l WHERE l.id=community_jobs.listing_id AND l.deleted=1)").run();
 await env.DB.prepare("DELETE FROM community_storage_reservations WHERE job_id IN(SELECT id FROM community_jobs WHERE status IN('failed','succeeded')) AND NOT EXISTS(SELECT 1 FROM community_files WHERE job_id=community_storage_reservations.job_id AND status!='deleted' AND role='input')").run();
 await env.DB.prepare("DELETE FROM community_delivery_receipts WHERE day<date('now','-30 days')").run();await env.DB.prepare("DELETE FROM community_daily_stats WHERE day<date('now','-30 days')").run();
}
export async function drainCommunityJobs(env:Bindings) {const jobs=(await env.DB.prepare("SELECT id FROM community_jobs WHERE (status='queued' OR (status='running' AND lease_until<=?)) AND stage!='receiving' ORDER BY created_at LIMIT 2").bind(Date.now()).all<{id:string}>()).results;for(const job of jobs)await processCommunityJob(env,job.id);await reconcileCommunityStorage(env);}
