import { type Board, type BoardElement } from '../shared/board-schema';
import type { DesignOperation } from '../shared/operations';
import { uid } from '../shared/schema';

export function BoardSelectionPanel({ board, ids, apply }: { board: Board; ids: string[]; apply: (actions: DesignOperation[]) => void }) {
  const selected = board.elements.filter(e => ids.includes(e.id)), active = selected[0];
  if (!active) return null;
  const update = (changes: Record<string, unknown>) => apply([{ op: 'upsert-board-elements', boardId: board.id, elements: selected.map(e => ({ ...e, ...changes })) as BoardElement[] }]);
  const transform = (changes: Record<string, unknown>) => apply([{ op: 'transform-board-elements', boardId: board.id, elementIds: ids, dx: 0, dy: 0, scaleX: 1, scaleY: 1, rotation: 0, flipX: false, flipY: false, ...changes } as DesignOperation]);
  return <div className="board-selection-panel"><strong>{ids.length} selected</strong>
    <label>Name<input aria-label="Element name" value={active.name} onChange={e => update({ name: e.target.value })}/></label>
    <div className="board-numbers">{(['x', 'y', 'width', 'height', 'rotation'] as const).map(key => <label key={key}>{key}<input aria-label={`Element ${key}`} type="number" value={Math.round(active[key] * 100) / 100} onChange={e => { const v = +e.target.value; if (!Number.isFinite(v)) return; if (key === 'x' || key === 'y') transform({ [key === 'x' ? 'dx' : 'dy']: v - active[key] }); else if (key === 'rotation') transform({ rotation: v - active.rotation }); else if (v > 0) transform({ [key === 'width' ? 'scaleX' : 'scaleY']: v / active[key] }); }}/></label>)}</div>
    {'stroke' in active && <><label>Stroke<input aria-label="Selection stroke" type="color" value={active.stroke.startsWith('#') ? active.stroke : '#26352d'} onChange={e => update({ stroke: e.target.value })}/></label><label>Fill<input aria-label="Selection fill" type="color" value={active.fill.startsWith('#') ? active.fill : '#ffffff'} onChange={e => update({ fill: e.target.value })}/><button onClick={() => update({ fill: 'none' })}>No fill</button></label><label>Line width<input aria-label="Selection line width" type="number" min=".1" max="256" value={active.strokeWidth} onChange={e => update({ strokeWidth: +e.target.value })}/></label><label>Sketch<input aria-label="Sketch roughness" type="range" min="0" max="3" step=".1" value={active.roughness} onChange={e => update({ roughness: +e.target.value })}/></label></>}
    <label>Opacity<input aria-label="Element opacity" type="range" min="0" max="1" step=".05" value={active.opacity} onChange={e => update({ opacity: +e.target.value })}/></label>
    <button onClick={() => update({ locked: !active.locked })}>{active.locked ? 'Unlock' : 'Lock'}</button><button onClick={() => transform({ flipX: true })}>Flip horizontal</button><button onClick={() => transform({ flipY: true })}>Flip vertical</button>
    <div><button onClick={() => apply([{ op: 'group-board-elements', boardId: board.id, elementIds: ids, groupId: uid(), frame: false }])}>Group</button><button onClick={() => apply([{ op: 'group-board-elements', boardId: board.id, elementIds: ids, groupId: uid(), frame: true }])}>Frame selection</button><button onClick={() => apply([{ op: 'ungroup-board-elements', boardId: board.id, elementIds: ids }])}>Ungroup</button></div>
    <label>Arrange<select aria-label="Arrange selection" value="" onChange={e => apply([{ op: 'reorder-board-elements', boardId: board.id, elementIds: ids, direction: e.target.value as 'front' }])}><option value="">Choose order</option>{['front', 'back', 'forward', 'backward'].map(v => <option key={v}>{v}</option>)}</select></label>
    <label>Align<select aria-label="Align selection" value="" onChange={e => apply([{ op: 'align-board-elements', boardId: board.id, elementIds: ids, alignment: e.target.value as 'left' }])}><option value="">Choose alignment</option>{['left', 'center', 'right', 'top', 'middle', 'bottom', 'horizontal', 'vertical'].map(v => <option key={v}>{v}</option>)}</select></label>
    {active.type === 'path' && <><button onClick={() => update({ commands: [...active.commands.filter(c => c.op !== 'Z'), ...(active.commands.at(-1)?.op === 'Z' ? [] : [{ op: 'Z' }])] })}>{active.commands.at(-1)?.op === 'Z' ? 'Open path' : 'Close path'}</button><button onClick={() => { const commands = active.commands.map((c, i) => { if (c.op !== 'L' || i === 0) return c; const prev = active.commands[i - 1]; if (!('x' in prev)) return c; return { op: 'C' as const, x1: prev.x + (c.x - prev.x) / 3, y1: prev.y + (c.y - prev.y) / 3, x2: prev.x + 2 * (c.x - prev.x) / 3, y2: prev.y + 2 * (c.y - prev.y) / 3, x: c.x, y: c.y }; }); update({ commands }); }}>Curve segments</button></>}
    <details><summary>Layers</summary>{[...board.elements].reverse().map(e => <div key={e.id}><span>{e.name}</span><button aria-label={`Toggle ${e.name} visibility`} onClick={() => apply([{ op: 'upsert-board-elements', boardId: board.id, elements: [{ ...e, visible: !e.visible }] }])}>{e.visible ? 'Hide' : 'Show'}</button></div>)}</details>
  </div>;
}
