import {readMotionArchive} from '../shared/motion-import';
import {useEffect,useMemo,useState} from 'react';
import {uid,type DesignDocument,type AssetRef} from '../shared/schema';
import {characterInstanceSchema,type Character,type BonePose} from '../shared/character-schema';
import {newCharacter,addCharacterLayer,keyBone} from '../shared/character-editing';
import {evaluateCharacter} from '../shared/character-runtime';
import {worldMatrices,inverse,point,identity} from '../shared/character-math';
import {CharacterView} from './character-view';
import {CharacterRigPanel} from './character-rig-panel';
import {CharacterMeshPanel} from './character-mesh-panel';
import {MotionClipPanel} from './motion-clip-panel';
import {CharacterConstraintsPanel} from './character-constraints-panel';
import {CharacterCompositionPanel} from './character-composition-panel';
import {api,message} from './api';
import './character-editor.css';
export function CharacterEditor({doc,pageId,projectId,nodeId,change,externalError,undo,redo}:{doc:DesignDocument;pageId:string;projectId:string;nodeId?:string;externalError?:string;undo:()=>void;redo:()=>void;change:(fn:(d:DesignDocument)=>void)=>void}){
 const [active,setActive]=useState(doc.pages.flatMap(p=>p.nodes).find(n=>n.id===nodeId)?.character?.characterId??doc.characters?.[0]?.id??''),[mode,setMode]=useState('Setup'),[tab,setTab]=useState('Rig'),[boneId,setBone]=useState(''),[clipId,setClip]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[autoKey,setAutoKey]=useState(false),[ghost,setGhost]=useState(false),[draft,setDraft]=useState<Partial<BonePose>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const c=doc.characters?.find(c=>c.id===active),instanceNode=doc.pages.flatMap(p=>p.nodes).find(n=>n.id===nodeId&&n.character?.characterId===active)??doc.pages.find(p=>p.id===pageId)?.nodes.find(n=>n.character?.characterId===active);
 const instance=useMemo(()=>mode==='Compose'&&instanceNode?.character?instanceNode.character:characterInstanceSchema.parse({characterId:active||'preview',clipId:mode==='Animate'?clipId||undefined:undefined}),[mode,instanceNode?.character,active,clipId]);
 const duration=mode==='Compose'?doc.timeline?.duration??10:c?.clips.find(x=>x.id===clipId)?.duration??2;
 useEffect(()=>{if(!playing)return;let frame=0,previous=performance.now();const tick=(now:number)=>{setTime(t=>(t+(now-previous)/1000)%duration);previous=now;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,duration]);
 const pose=useMemo(()=>c?evaluateCharacter(c,instance,mode==='Setup'?0:time):null,[c,instance,mode,time]);
 const selected=c?.bones.find(b=>b.id===boneId)??c?.bones[0];
 const edit=(fn:(c:Character)=>void)=>{setError('');change(d=>{const target=d.characters?.find(x=>x.id===active);if(!target)throw new Error('Character was removed. Reopen motion.');fn(target);});};
 const seek=(n:number)=>{setPlaying(false);setDraft({});setTime(n);};
 const poseChange=(patch:Partial<BonePose>)=>{if(!selected)return;setDraft(d=>({...d,...patch}));if(autoKey&&clipId)edit(c=>keyBone(c,clipId,selected.id,time,patch));};
 const shown=useMemo(()=>{if(!c||!pose||!selected||!Object.keys(draft).length)return c;return {...c,constraints:[],bones:c.bones.map(b=>({...b,...pose.bones[b.id],...(b.id===selected.id?draft:{})}))};},[c,pose,selected,draft]);
 const shownInstance=Object.keys(draft).length?characterInstanceSchema.parse({characterId:active||'preview'}):instance;
 async function upload(files:FileList|null){if(!files||!c)return;setBusy(true);setError('');const assets:{asset:AssetRef;width:number;height:number}[]=[];
  try{for(const file of Array.from(files)){const image=await createImageBitmap(file);const width=image.width,height=image.height;image.close();const form=new FormData();form.append('file',file);const {asset}=await api<{asset:AssetRef}>(`/api/projects/${projectId}/assets`,{method:'POST',body:form});assets.push({asset,width,height});}
   change(d=>{const target=d.characters?.find(x=>x.id===active);if(!target)throw new Error('Rig was removed during upload. Assets remain available in the project.');for(const {asset,width,height}of assets){if(!d.assets.some(a=>a.id===asset.id))d.assets.push(asset);addCharacterLayer(target,asset.id,asset.name,Math.min(width,20000),Math.min(height,20000));}});
  }catch(e){setError(message(e));}finally{setBusy(false);}
 }
 async function importPackage(file:File){setBusy(true);setError('');try{if(file.size>32*1024*1024)throw new Error('Motion package exceeds 32 MiB');const imported=await readMotionArchive(new Uint8Array(await file.arrayBuffer())),assets:AssetRef[]=[],mapping=new Map<string,string>();
 for(const asset of imported.assets){const blob=await (await fetch(asset.url)).blob(),form=new FormData();form.append('file',blob,asset.name);const result=await api<{asset:AssetRef}>(`/api/projects/${projectId}/assets`,{method:'POST',body:form});assets.push(result.asset);mapping.set(asset.id,result.asset.id);}
 const characters=imported.characters!.map(c=>({...c,id:uid(),attachments:c.attachments.map(a=>({...a,assetId:a.assetId?mapping.get(a.assetId):undefined,frames:a.frames?.map(id=>mapping.get(id)!)}))}));
 change(d=>{d.schemaVersion=2;d.timeline??={duration:10,fps:30,tracks:[]};d.assets.push(...assets);(d.characters??=[]).push(...characters);for(const c of characters)d.pages.find(p=>p.id===pageId)!.nodes.push({id:uid(),name:c.name,type:'character',x:40,y:40,width:c.width,height:c.height,character:characterInstanceSchema.parse({characterId:c.id,clipId:c.clips[0]?.id})});});setActive(characters[0].id);
 }catch(e){setError(message(e));}finally{setBusy(false);}}
 return <div className="character-editor"><header className="character-toolbar"><label>Import native motion ZIP<input aria-label="Import native motion ZIP" type="file" accept=".zip" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void importPackage(file);e.target.value='';}}/></label><button onClick={()=>{setDraft({});undo();}}>Undo motion edit</button><button onClick={()=>{setDraft({});redo();}}>Redo motion edit</button><label>Character<select value={active} onChange={e=>{setActive(e.target.value);setBone('');setClip('');setDraft({});}}><option value="">Choose character</option>{doc.characters?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button onClick={()=>{const c=newCharacter();change(d=>{d.schemaVersion=2;d.timeline??={duration:10,fps:30,tracks:[]};(d.characters??=[]).push(c);d.pages.find(p=>p.id===pageId)!.nodes.push({id:uid(),name:c.name,type:'character',x:40,y:40,width:512,height:512,character:characterInstanceSchema.parse({characterId:c.id})});});setActive(c.id);}}>New character</button>{c&&<button onClick={()=>change(d=>d.pages.find(p=>p.id===pageId)!.nodes.push({id:uid(),name:c.name,type:'character',x:60,y:60,width:c.width,height:c.height,character:characterInstanceSchema.parse({characterId:c.id})}))}>Insert another instance</button>}</header>
 {(error||externalError)&&<p role="alert">{error||externalError}</p>}
 {!c?<p>Create a character, then import PNG layers or attach images from this project.</p>:<><nav aria-label="Character mode">{['Setup','Animate','Compose'].map(m=><button key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setDraft({});setPlaying(false);}}>{m}</button>)}</nav>
 <div className="character-columns"><aside>
 <label>Character name<input value={c.name} onChange={e=>edit(c=>{c.name=e.target.value;})}/></label>
 {mode==='Setup'&&<><label>Import PNG layers<input aria-label="Import character images" disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label><p>Images start at the root; use offsets to assemble cropped parts.</p><nav aria-label="Setup tools">{['Rig','Mesh','Constraints'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav></>}
 {mode==='Setup'&&tab==='Mesh'?<CharacterMeshPanel c={c} assets={doc.assets} edit={edit}/>:mode==='Setup'&&tab==='Constraints'?<CharacterConstraintsPanel c={c} edit={edit}/>:mode==='Compose'&&instanceNode?.character?<CharacterCompositionPanel c={c} instance={instanceNode.character} edit={fn=>change(d=>fn(d.pages.flatMap(p=>p.nodes).find(n=>n.id===instanceNode.id)!.character!))}/>:<CharacterRigPanel c={c} boneId={selected!.id} select={id=>{setBone(id);setDraft({});}} edit={edit} assets={doc.assets} animate={mode==='Animate'} pose={mode==='Animate'?{...pose!.bones[selected!.id],...draft}:undefined} poseChange={poseChange}/>}
 {mode==='Animate'&&<><label><input type="checkbox" checked={autoKey} onChange={e=>setAutoKey(e.target.checked)}/>Auto-key {autoKey?'on':'off'}</label><button disabled={!clipId} onClick={()=>{edit(c=>keyBone(c,clipId,selected!.id,time,{...pose!.bones[selected!.id],...draft}));setDraft({});}}>Key selected pose</button><button onClick={()=>setDraft({})}>Discard pose preview</button><label><input type="checkbox" checked={ghost} onChange={e=>setGhost(e.target.checked)}/>Ghost previous / next pose</label></>}
 </aside><main><div className="character-stage" style={{aspectRatio:`${c.width}/${c.height}`}}>
 {ghost&&mode==='Animate'&&[-.1,.1].map(offset=><div key={offset} style={{position:'absolute',inset:0,opacity:.15,pointerEvents:'none'}}><CharacterView character={c} instance={instance} assets={doc.assets} time={Math.max(0,time+offset)}/></div>)}
 <CharacterView character={shown!} instance={shownInstance} assets={doc.assets} time={mode==='Setup'?0:time} playback={playing}/>
 {mode!=='Compose'&&<svg className="character-bones" viewBox={`0 0 ${c.width} ${c.height}`} onPointerDown={e=>{const id=(e.target as Element).getAttribute('data-bone');if(id)setBone(id);}}>{ghost&&selected&&mode==='Animate'&&<polyline fill="none" stroke="#7c3aed" strokeWidth="2" points={Array.from({length:21},(_,n)=>{const pose=evaluateCharacter(c,instance,n/20*duration);return point(worldMatrices(c.bones,pose.bones)[selected.id],[selected.length,0]).join(',');}).join(' ')}/>}
 {mode==='Setup'&&c.constraints.filter(x=>x.type==='ik'&&!x.targetBoneId).map(control=><circle key={control.id} cx={control.target[0]} cy={control.target[1]} r="9" fill="#16a34a" aria-label={`${control.name} target`} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerUp={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;e.currentTarget.releasePointerCapture(e.pointerId);const ctm=e.currentTarget.ownerSVGElement?.getScreenCTM();if(!ctm)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());edit(c=>{c.constraints.find(x=>x.id===control.id)!.target=[p.x,p.y];});}}/>)}
 {(()=>{const world=worldMatrices(c.bones,pose!.bones);return c.bones.map(b=>{const start=point(world[b.id],[0,0]),end=point(world[b.id],[b.length,0]);return <g key={b.id} stroke={selected?.id===b.id?'#dc2626':'#2563eb'} strokeWidth="3"><line x1={start[0]} y1={start[1]} x2={end[0]} y2={end[1]} data-bone={b.id}/><circle data-bone={b.id} cx={start[0]} cy={start[1]} r="7" fill="white" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setBone(b.id);}} onPointerUp={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;e.currentTarget.releasePointerCapture(e.pointerId);const svg=e.currentTarget.ownerSVGElement!,ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());try{const local=point(inverse(b.parentId?world[b.parentId]:identity()),[p.x,p.y]);if(mode==='Animate')poseChange({x:local[0],y:local[1]});else edit(c=>Object.assign(c.bones.find(x=>x.id===b.id)!,{x:local[0],y:local[1]}));}catch(err){setError(message(err));}}}/></g>;});})()}</svg>}
 </div><div className="character-toolbar"><button disabled={mode==='Setup'} onClick={()=>{setDraft({});setPlaying(v=>!v);}}>{playing?'Pause':'Play'}</button><input aria-label="Character playback time" type="range" min="0" max={duration} step=".01" value={time} onChange={e=>seek(e.target.valueAsNumber)}/><output>{time.toFixed(2)}s</output></div></main>
 <aside>{mode==='Animate'?<MotionClipPanel c={c} clipId={clipId} choose={id=>{setClip(id);seek(0);}} time={time} seek={seek} edit={edit}/>:<><p>{mode==='Setup'?'Setup changes the reusable rig. Animate adds clip keys. Compose changes only this scene instance.':'Placements blend in list order. Bone masks include descendants. Preview time here is scene time.'}</p><label>Rig width<input type="number" value={c.width} onChange={e=>edit(c=>{c.width=e.target.valueAsNumber;})}/></label><label>Rig height<input type="number" value={c.height} onChange={e=>edit(c=>{c.height=e.target.valueAsNumber;})}/></label><p>Save and undo use the project editor controls. Close this workspace to review the full scene.</p></>}</aside></div>
 </>}
 </div>;
}
