import {useEffect,useRef,useState} from 'react';
import {uid,type AssetRef} from '../shared/schema';
import type {Character,Attachment} from '../shared/character-schema';
import {gridMesh} from '../shared/character-editing';
export function CharacterMeshPanel({c,edit,assets}:{c:Character;edit:(fn:(c:Character)=>void)=>void;assets:AssetRef[]}){
 const worker=useRef<Worker|null>(null),[pending,setPending]=useState(false),[error,setError]=useState('');useEffect(()=>()=>worker.current?.terminate(),[]);
 const [id,setId]=useState(''),[vertex,setVertex]=useState(0),[bone,setBone]=useState(c.bones[0].id),[weight,setWeight]=useState(1),[radius,setRadius]=useState(24),[paint,setPaint]=useState(false),[skinId,setSkin]=useState('');
 const a=c.attachments.find(x=>x.id===id)??c.attachments[0],mesh=a?.mesh??c.attachments.find(x=>x.id===a?.sourceMeshId)?.mesh;
 const update=(fn:(a:Attachment)=>void)=>edit(c=>fn(c.attachments.find(x=>x.id===a!.id)!));
 const paintAt=(x:number,y:number)=>update(a=>{if(!a.mesh)throw new Error('Make this linked mesh independent before painting.');const m=a.mesh;m.weights??=m.vertices.map(()=>[{boneId:c.slots.find(s=>s.id===a.slotId)!.boneId,weight:1}]);m.vertices.forEach((v,i)=>{if(Math.hypot(v[0]-x,v[1]-y)>radius)return;const rest=m.weights![i].filter(w=>w.boneId!==bone).sort((a,b)=>b.weight-a.weight).slice(0,3),sum=rest.reduce((s,w)=>s+w.weight,0);m.weights![i]=sum?[...rest.map(w=>({...w,weight:w.weight/sum*(1-weight)})),{boneId:bone,weight}]:[{boneId:bone,weight:1}];});});
 const slot=c.slots.find(s=>s.id===a?.slotId);
 const auto=()=>{if(!a?.mesh)return;const snapshot=JSON.stringify(c),attachmentId=a.id,jobId=uid();setPending(true);setError('');worker.current?.terminate();const task=new Worker('/studio-character-worker.js');worker.current=task;task.onmessage=event=>{if(event.data.jobId!==jobId)return;task.terminate();setPending(false);if(event.data.error){setError(event.data.error);return;}edit(current=>{if(JSON.stringify(current)!==snapshot)throw new Error('Rig changed during weight calculation. Run it again.');current.attachments.find(x=>x.id===attachmentId)!.mesh!.weights=event.data.weights;});};task.onerror=()=>{task.terminate();setPending(false);setError('Weight worker failed. Use the weight brush or retry.');};task.postMessage({jobId,character:c,attachmentId});};
 return <section aria-label="Attachments and mesh">{error&&<p role="alert">{error}</p>}<label>Attachment<select value={a?.id??''} onChange={e=>{setId(e.target.value);setVertex(0);}}>{c.attachments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {a&&<><label>Name<input value={a.name} onChange={e=>update(a=>{a.name=e.target.value;})}/></label><label>Type<select value={a.kind} onChange={e=>update(a=>{a.kind=e.target.value as Attachment['kind'];if(a.kind==='mesh'&&!a.mesh)a.mesh=gridMesh(a.width,a.height);if(['clipping','bounds'].includes(a.kind))a.points??=[[0,0],[a.width,0],[a.width,a.height],[0,a.height]];if(a.kind==='sequence'){a.frames??=a.assetId?[a.assetId]:[];a.fps??=12;}})}>{['region','mesh','sequence','clipping','bounds'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Image<select value={a.assetId??''} onChange={e=>update(a=>{a.assetId=e.target.value;})}>{assets.filter(x=>x.mimeType.startsWith('image/')).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {(['x','y','width','height','rotation'] as const).map(p=><label key={p}>{p}<input type="number" value={a[p]} onChange={e=>update(a=>{a[p]=e.target.valueAsNumber;})}/></label>)}
 {[0,1].map(axis=><label key={axis}>Pivot {axis?'Y':'X'}<input type="number" step=".1" value={a.pivot[axis]} onChange={e=>update(a=>{a.pivot[axis]=e.target.valueAsNumber;})}/></label>)}
 {slot&&<><label>Slot bone<select value={slot.boneId} onChange={e=>edit(c=>{c.slots.find(s=>s.id===slot.id)!.boneId=e.target.value;})}>{c.bones.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Blend<select value={slot.blend} onChange={e=>edit(c=>{c.slots.find(s=>s.id===slot.id)!.blend=e.target.value as 'normal';})}>{['normal','multiply','screen','add'].map(x=><option key={x}>{x}</option>)}</select></label><label>Draw order<input type="number" min="0" max={c.slots.length-1} value={c.slots.indexOf(slot)} onChange={e=>edit(c=>{const old=c.slots.findIndex(s=>s.id===slot.id),[s]=c.slots.splice(old,1);c.slots.splice(e.target.valueAsNumber,0,s);})}/></label></>}
 <button onClick={()=>update(a=>{if(c.clips.some(clip=>clip.channels.some(ch=>ch.targetId===a.id&&ch.property==='deform')))throw new Error('Remove or remap deformation keys before changing topology.');a.kind='mesh';a.mesh={...gridMesh(a.width,a.height),version:(a.mesh?.version??0)+1};delete a.sourceMeshId;})}>Create 4 × 4 mesh</button>
 <button onClick={()=>edit(c=>{const copy=structuredClone(a);copy.id=uid();copy.name+=' variant';if(a.mesh){copy.sourceMeshId=a.id;delete copy.mesh;}c.attachments.push(copy);setId(copy.id);})}>Duplicate as skin variant</button>
 {mesh&&<><svg viewBox={`-10 -10 ${a.width+20} ${a.height+20}`} style={{width:'100%',maxHeight:260,background:'#e2e8f0',touchAction:'none'}} aria-label="Mesh weight canvas" onPointerDown={e=>{const box=e.currentTarget.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*(a.width+20)-10,y=(e.clientY-box.top)/box.height*(a.height+20)-10;if(paint)paintAt(x,y);else setVertex(mesh.vertices.reduce((best,v,i)=>Math.hypot(v[0]-x,v[1]-y)<Math.hypot(mesh.vertices[best][0]-x,mesh.vertices[best][1]-y)?i:best,0));}}>{Array.from({length:mesh.triangles.length/3},(_,i)=><polygon key={i} points={mesh.triangles.slice(i*3,i*3+3).map(j=>mesh.vertices[j].join(',')).join(' ')} fill="none" stroke="#94a3b8" strokeWidth=".5"/>)}{mesh.vertices.map((v,i)=><circle key={i} cx={v[0]} cy={v[1]} r={i===vertex?4:2} fill={`rgb(${Math.round((mesh.weights?.[i]?.find(w=>w.boneId===bone)?.weight??0)*255)},60,180)`}/>)}</svg>
 <label>Vertex<input type="number" min="0" max={mesh.vertices.length-1} value={vertex} onChange={e=>setVertex(Math.max(0,Math.min(mesh.vertices.length-1,e.target.valueAsNumber||0)))}/></label>
 {(['vertices','uv'] as const).flatMap(field=>[0,1].map(axis=><label key={field+axis}>{field} {axis?'Y':'X'}<input type="number" step=".01" value={mesh[field][vertex]?.[axis]??0} onChange={e=>update(a=>{if(!a.mesh)throw new Error('Edit the linked source mesh or make independent.');a.mesh[field][vertex][axis]=e.target.valueAsNumber;})}/></label>))}
 <button disabled={!a.sourceMeshId} onClick={()=>update(a=>{a.mesh=structuredClone(mesh);delete a.sourceMeshId;})}>Make mesh independent</button>
 <button disabled={pending||!a.mesh} onClick={auto}>{pending?'Calculating weights…':'Auto weight by nearest bones'}</button>
 <label>Influence bone<select value={bone} onChange={e=>setBone(e.target.value)}>{c.bones.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Weight<input type="range" min="0" max="1" step=".05" value={weight} onChange={e=>setWeight(e.target.valueAsNumber)}/></label><label>Brush radius<input type="number" min="1" max="500" value={radius} onChange={e=>setRadius(e.target.valueAsNumber)}/></label><label><input type="checkbox" checked={paint} onChange={e=>setPaint(e.target.checked)}/>Paint weights on canvas</label><button onClick={()=>paintAt(...mesh.vertices[vertex])}>Apply brush at selected vertex</button><p>Weights normalize to 1; at most four influences. Canvas color shows selected bone influence.</p>
 </>}
 {a.kind==='sequence'&&<><label>Frames (asset IDs in order)<textarea value={a.frames?.join('\n')??''} onChange={e=>update(a=>{a.frames=e.target.value.split(/\s+/).filter(Boolean);})}/></label><label>FPS<input type="number" min="1" max="60" value={a.fps??12} onChange={e=>update(a=>{a.fps=e.target.valueAsNumber;})}/></label></>}
 {a.points&&<><label>Polygon points JSON<textarea key={a.id} defaultValue={JSON.stringify(a.points)} onBlur={e=>update(a=>{a.points=JSON.parse(e.target.value);})}/></label>{a.kind==='clipping'&&<><label>End slot<select value={a.clipEndSlotId??''} onChange={e=>update(a=>{a.clipEndSlotId=e.target.value||undefined;})}><option value="">Last slot</option>{c.slots.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><input type="checkbox" checked={a.inverse??false} onChange={e=>update(a=>{a.inverse=e.target.checked;})}/>Inverse clipping</label></>}</>}
 <details><summary>Skins</summary><button onClick={()=>{const id=uid();edit(c=>c.skins.push({id,name:'Skin',attachments:{}}));setSkin(id);}}>New skin</button><select aria-label="Edit skin" value={skinId} onChange={e=>setSkin(e.target.value)}><option value="">Choose skin</option>{c.skins.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{skinId&&c.skins.some(s=>s.id===skinId)&&<><input aria-label="Skin name" value={c.skins.find(s=>s.id===skinId)!.name} onChange={e=>edit(c=>{c.skins.find(s=>s.id===skinId)!.name=e.target.value;})}/><button onClick={()=>edit(c=>{c.skins.find(s=>s.id===skinId)!.attachments[a.slotId]=a.id;})}>Use attachment in skin</button></>}</details>
 </>}
 </section>;
}
