import {useRef,useState} from 'react';
import {uid} from '../shared/schema';
import {placementSchema,type Character,type CharacterInstance,type Placement} from '../shared/character-schema';
export function CharacterCompositionPanel({c,instance,edit}:{c:Character;instance:CharacterInstance;edit:(fn:(i:CharacterInstance)=>void)=>void}){
 const drag=useRef<{x:number;start:number;end:number;id:string;edge:boolean}|null>(null);const duration=Math.max(1,...instance.placements.map(p=>p.end));const [id,setId]=useState(''),p=instance.placements.find(x=>x.id===id)??instance.placements[0];
 const update=(fn:(p:Placement)=>void)=>edit(i=>fn(i.placements.find(x=>x.id===p!.id)!));
 return <section aria-label="Scene composition"><label>Skin<select value={instance.skinId??''} onChange={e=>edit(i=>{i.skinId=e.target.value||undefined;})}><option value="">Setup attachments</option>{c.skins.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Default clip<select value={instance.clipId??''} onChange={e=>edit(i=>{i.clipId=e.target.value||undefined;})}><option value="">Setup pose</option>{c.clips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <button disabled={!c.clips.length} onClick={()=>{const id=uid();edit(i=>i.placements.push(placementSchema.parse({id,clipId:c.clips[0].id,start:0,end:c.clips[0].duration})));setId(id);}}>Place clip in scene</button>
 <svg viewBox={`0 0 600 ${Math.max(1,instance.placements.length)*32}`} aria-label="Composition timeline" style={{width:'100%',touchAction:'none',background:'#eef2ff'}}>{instance.placements.map((placement,index)=><g key={placement.id}><rect x={placement.start/duration*600} y={index*32+2} width={(placement.end-placement.start)/duration*600} height="26" rx="3" fill={p?.id===placement.id?'#7c3aed':'#6366f1'} onPointerDown={e=>{setId(placement.id);const box=e.currentTarget.ownerSVGElement!.getBoundingClientRect();drag.current={id:placement.id,x:e.clientX,start:placement.start,end:placement.end,edge:e.clientX>box.left+placement.end/duration*box.width-10};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const d=drag.current;if(!d||!e.currentTarget.hasPointerCapture(e.pointerId))return;e.currentTarget.releasePointerCapture(e.pointerId);drag.current=null;const width=e.currentTarget.ownerSVGElement!.getBoundingClientRect().width,delta=(e.clientX-d.x)/width*duration;edit(i=>{const p=i.placements.find(p=>p.id===d.id)!;if(d.edge)p.end=Math.max(p.start+.01,d.end+delta);else{p.start=Math.max(0,d.start+delta);p.end=d.end+p.start-d.start;}});}} onPointerCancel={()=>{drag.current=null;}}/><text x={placement.start/duration*600+4} y={index*32+20} fill="white" fontSize="12" pointerEvents="none">{c.clips.find(c=>c.id===placement.clipId)?.name}</text></g>)}</svg><p>Drag a block to move it; drag its right edge to trim. Numeric fields support the same edits.</p>
 <label>Placement<select value={p?.id??''} onChange={e=>setId(e.target.value)}>{instance.placements.map((p,j)=><option key={p.id} value={p.id}>{j+1}. {c.clips.find(x=>x.id===p.clipId)?.name} · {p.start}s–{p.end}s</option>)}</select></label>
 {p&&<><label>Animation<select value={p.clipId} onChange={e=>update(p=>{p.clipId=e.target.value;})}>{c.clips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{(['start','end','sourceStart','speed','weight','fadeIn','fadeOut'] as const).map(field=><label key={field}>{field}<input type="number" step=".1" value={p[field]} onChange={e=>update(p=>{p[field]=e.target.valueAsNumber;})}/></label>)}<label><input type="checkbox" checked={p.loop} onChange={e=>update(p=>{p.loop=e.target.checked;})}/>Loop clip</label><label>Blend<select value={p.blend} onChange={e=>update(p=>{p.blend=e.target.value as 'override';})}><option>override</option><option>additive</option></select></label><label>Bone mask (empty = all)<select multiple value={p.mask??[]} onChange={e=>{const mask=Array.from(e.target.selectedOptions,o=>o.value);update(p=>{p.mask=mask.length?mask:undefined;});}}>{c.bones.map(b=><option key={b.id} value={b.id}>{b.name} + descendants</option>)}</select></label><button onClick={()=>edit(i=>{const index=i.placements.findIndex(x=>x.id===p.id);if(index>0)[i.placements[index-1],i.placements[index]]=[i.placements[index],i.placements[index-1]];})}>Move earlier in blend order</button><button onClick={()=>edit(i=>{i.placements=i.placements.filter(x=>x.id!==p.id);})}>Remove placement</button></>}
 {c.constraints.filter(x=>x.type==='slider').map(x=><label key={x.id}>{x.name}<input type="range" min="0" max="1" step=".01" value={instance.controls?.[x.id]??x.value} onChange={e=>edit(i=>{i.controls??={};i.controls[x.id]=e.target.valueAsNumber;})}/></label>)}
 {(['click','hover'] as const).map(trigger=><label key={trigger}>{trigger} animation<select value={instance.interactions.find(x=>x.trigger===trigger)?.clipId??''} onChange={e=>edit(i=>{i.interactions=i.interactions.filter(x=>x.trigger!==trigger);if(e.target.value)i.interactions.push({trigger,clipId:e.target.value});})}><option value="">None</option>{c.clips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}
 </section>;
}
