import {useState} from 'react';
import {uid} from '../shared/schema';
import {constraintSchema,type Character,type Constraint} from '../shared/character-schema';
export function CharacterConstraintsPanel({c,edit}:{c:Character;edit:(fn:(c:Character)=>void)=>void}){
 const [id,setId]=useState(''),[type,setType]=useState<Constraint['type']>('ik');const control=c.constraints.find(x=>x.id===id)??c.constraints[0];
 const update=(fn:(x:Constraint)=>void)=>edit(c=>fn(c.constraints.find(x=>x.id===control!.id)!));
 return <section aria-label="Character constraints"><select aria-label="New constraint type" value={type} onChange={e=>setType(e.target.value as Constraint['type'])}>{['ik','transform','path','physics','slider'].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{const id=uid();edit(c=>c.constraints.push(constraintSchema.parse({id,name:type,type,bones:[c.bones[0].id],...(type==='transform'?{targetBoneId:c.bones[1]?.id}:{}),...(type==='path'?{path:[[0,0],[100,0],[100,100],[200,100]]}:{}),...(type==='slider'?{clipId:c.clips[0]?.id}:{})})));setId(id);}}>Add constraint</button>
 <label>Constraint<select value={control?.id??''} onChange={e=>setId(e.target.value)}>{c.constraints.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {control&&<><label>Name<input value={control.name} onChange={e=>update(x=>{x.name=e.target.value;})}/></label><label>Bones (in chain order)<select multiple value={control.bones} onChange={e=>{const ids=Array.from(e.target.selectedOptions,o=>o.value);update(x=>{x.bones=ids;});}}>{c.bones.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
 <label>Target bone<select value={control.targetBoneId??''} onChange={e=>update(x=>{x.targetBoneId=e.target.value||undefined;})}><option value="">Point / manual value</option>{c.bones.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
 {[0,1].map(axis=><label key={axis}>Target {axis?'Y':'X'}<input type="number" value={control.target[axis]} onChange={e=>update(x=>{x.target[axis]=e.target.valueAsNumber;})}/></label>)}
 <label>Mix<input type="range" min="0" max="1" step=".01" value={control.mix} onChange={e=>update(x=>{x.mix=e.target.valueAsNumber;})}/></label>
 {control.type==='ik'&&<><label>Bend<select value={control.bend} onChange={e=>update(x=>{x.bend=e.target.value as 'positive';})}><option>positive</option><option>negative</option></select></label><label><input type="checkbox" checked={control.stretch} onChange={e=>update(x=>{x.stretch=e.target.checked;})}/>Stretch and squash</label></>}
 {['transform','slider'].includes(control.type)&&<><label>Source property<select value={control.sourceProperty} onChange={e=>update(x=>{x.sourceProperty=e.target.value as 'x';})}>{['x','y','rotation','scaleX','scaleY'].map(p=><option key={p}>{p}</option>)}</select></label><label>Factor<input type="number" value={control.factor} onChange={e=>update(x=>{x.factor=e.target.valueAsNumber;})}/></label></>}
 {control.type==='transform'&&<><label>Destination property<select value={control.destinationProperty} onChange={e=>update(x=>{x.destinationProperty=e.target.value as 'x';})}>{['x','y','rotation','scaleX','scaleY'].map(p=><option key={p}>{p}</option>)}</select></label><label>Space<select value={control.space} onChange={e=>update(x=>{x.space=e.target.value as 'world';})}><option>world</option><option>local</option></select></label>{(['min','max'] as const).map(p=><label key={p}>{p}<input type="number" value={control[p]??''} onChange={e=>update(x=>{x[p]=e.target.value===''?undefined:e.target.valueAsNumber;})}/></label>)}</>}
 {control.type==='path'&&<><label>Cubic path points JSON<textarea key={control.id} defaultValue={JSON.stringify(control.path)} onBlur={e=>update(x=>{x.path=JSON.parse(e.target.value);})}/></label>{(['position','spacing'] as const).map(p=><label key={p}>{p}<input type="number" min="0" max="1" step=".01" value={control[p]} onChange={e=>update(x=>{x[p]=e.target.valueAsNumber;})}/></label>)}</>}
 {control.type==='physics'&&(['stiffness','damping','mass','gravity','wind'] as const).map(p=><label key={p}>{p}<input type="number" step=".1" value={control[p]} onChange={e=>update(x=>{x[p]=e.target.valueAsNumber;})}/></label>)}
 {control.type==='slider'&&<><label>Pose clip<select value={control.clipId??''} onChange={e=>update(x=>{x.clipId=e.target.value;})}>{c.clips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Pose value<input type="range" min="0" max="1" step=".01" value={control.value} onChange={e=>update(x=>{x.value=e.target.valueAsNumber;})}/></label></>}
 <button onClick={()=>edit(c=>{c.constraints=c.constraints.filter(x=>x.id!==control.id);})}>Remove constraint</button></>}
 </section>;
}
