import { useEffect, useRef, useState } from 'react';
import { Bookmark, Search, Upload, SlidersHorizontal, Globe, X } from 'lucide-react';
import type { Project } from '../shared/schema';
import type { CommunityCollection, CommunityListing, CommunityProfile, CommunityJob } from '../shared/community';
import { api, post, message, ApiError, type User } from './api';
import { PublicNavigation } from './public-navigation';
import { Field, Modal } from './ui';
import { communitySignIn } from './community-navigation';
import { CommunityCard, CommunityDetail } from './community-detail';
import { CommunityProfileForm } from './community-profile';
import { CommunityPublishDialog } from './community-publish-dialog';
import { CommunitySearchDialog } from './community-search-dialog';
import { CommunityJobStatus } from './community-job-status';
import { useContextualSearch } from './contextual-search';
import { communityKinds, formatLabel, useCommunityResource, storedCommunityImport } from './community-client';
import { CommunityImpact } from './community-impact';
import { CommunityModeration } from './community-moderation';
import { registerCommunityBrowserTools } from './browser-design-tools';
import './community.css';
import { CommunityBookmarks } from './community-bookmarks';
type ListingsResponse = { listings: CommunityListing[]; nextCursor?: string | null; facets?: { formats: { format: string; count: number }[] } };
export function CommunityApp() {
  const [url, setUrl] = useState(() => new URL(location.href)), [user, setUser] = useState<User | null>(null), [authReady, setAuthReady] = useState(false);
  const [filterOpen, setFilterOpen] = useState(false), [publishProject, setPublishProject] = useState<Project | null>(null), [publishListing, setPublishListing] = useState<CommunityListing | undefined>(), [picker, setPicker] = useState(false), [error, setError] = useState(''), [importOperation, setImportOperation] = useState<string | null>(null);
  const deployment = useCommunityResource<{ community?: { enabled: boolean } }>('/api/config');
  useEffect(() => { if (user) setImportOperation(storedCommunityImport(user.id)); else setImportOperation(null); }, [user?.id]);
  const search = useContextualSearch(deployment.data?.community?.enabled !== false), path = url.pathname.replace(/\/$/, '');
  const privatePage = ['/community/saved','/community/publishing','/community/impact','/community/moderation'].includes(path);
  const account = useCommunityResource<{ profile: CommunityProfile | null; moderator: boolean }>(user ? '/api/community/me/profile' : null);
  useEffect(() => { const controller = new AbortController(); void api<{ user: User | null }>('/api/auth/me', { signal: controller.signal }).then(data => setUser(data.user)).catch(() => {}).finally(() => { if (!controller.signal.aborted) setAuthReady(true); }); return () => controller.abort(); }, []);
  useEffect(() => { const update = () => setUrl(new URL(location.href)); window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update); }, []);
  useEffect(() => {
    const context = (document as Document & { modelContext?: Parameters<typeof registerCommunityBrowserTools>[0] }).modelContext || (navigator as Navigator & { modelContext?: Parameters<typeof registerCommunityBrowserTools>[0] }).modelContext;
    if (context) return registerCommunityBrowserTools(context);
  }, []);
  const listingId = /^\/community\/designs\/([^/]+)$/.exec(path)?.[1], handle = /^\/community\/creators\/([^/]+)$/.exec(path)?.[1];
  const listing = useCommunityResource<{ listing: CommunityListing }>(listingId ? `/api/community/listings/${encodeURIComponent(listingId)}` : null);
  const creator = useCommunityResource<{ profile: CommunityProfile; listings: CommunityListing[] }>(handle ? `/api/community/creators/${encodeURIComponent(handle)}` : null);
  function filter(name: string, value: string) { const next = new URL(location.href); if (value) next.searchParams.set(name, value); else next.searchParams.delete(name); next.searchParams.delete('cursor'); history.pushState(null, '', next.pathname + next.search); setUrl(next); }
  async function chooseProject(id: string, existing?: CommunityListing) { try { const result = await api<{ project: Project }>(`/api/projects/${encodeURIComponent(id)}`); setPublishProject(result.project); setPublishListing(existing); setPicker(false); } catch (error) { setError(message(error)); } }
  const startPublish = () => { if (user) setPicker(true); else communitySignIn('/community/publishing'); };
  return <CommunityBookmarks accountId={user?.id}><div className="community-shell"><PublicNavigation active="community"/><main className="community-main">
    <nav className="community-tabs" aria-label="Community navigation"><a href="/community" aria-current={path === '/community' ? 'page' : undefined}><Globe size={16}/> Explore</a><a href="/community/saved" aria-current={path.endsWith('/saved') ? 'page' : undefined}><Bookmark size={16}/> Saved</a><a href="/community/publishing" aria-current={path.endsWith('/publishing') ? 'page' : undefined}>Publishing</a><a href="/community/impact" aria-current={path.endsWith('/impact') ? 'page' : undefined}>Impact</a>{account.data?.moderator && <a href="/community/moderation">Moderation</a>}<button className="button small" aria-label="Search Community" onClick={() => search.setOpen(true)}><Search size={16}/><span>Search</span><kbd>Ctrl K</kbd></button></nav>
    {error && <p role="alert">{error}</p>}
    {deployment.data?.community?.enabled === false && path !== '/community/moderation' ? <section className="community-empty"><h1>Community is unavailable</h1><p>Community is not enabled on this deployment. Your workspace and existing Share links remain available.</p><a className="button" href="/">Return to workspace</a></section> : privatePage && !authReady ? <p role="status">Checking your account…</p> : privatePage && !user ? <section className="community-empty"><h1>{path.endsWith('saved') ? 'Your saved designs' : 'Your Community workspace'}</h1><p>Sign in to manage your private collection, publishing and impact.</p><button className="button primary" onClick={() => communitySignIn()}>Sign in to continue</button></section> : listingId ? <>{listing.loading && <div className="community-skeleton" aria-label="Loading design"/>}{listing.error && <section className="community-empty"><h1>This design is unavailable</h1><p role="alert">{listing.error}</p><a href="/community" className="button">Explore Community</a></section>}{listing.data && <CommunityDetail listing={listing.data.listing} signedIn={!!user}/>}</> : handle ? <>{creator.error && <p role="alert">{creator.error}</p>}{creator.loading && <p role="status">Loading creator…</p>}{creator.data && <><section className="community-creator"><span className="avatar">{creator.data.profile.displayName.slice(0,1).toUpperCase()}</span><div><h1>{creator.data.profile.displayName}</h1><p>@{creator.data.profile.handle}</p><p>{creator.data.profile.bio}</p><div className="community-tags">{creator.data.profile.badges.map(badge => <span key={badge.badge}>{badge.badge.replaceAll('-', ' ')}</span>)}</div></div></section><CommunityBrowse query={`?creator=${encodeURIComponent(handle)}`} saved={false} signedIn={!!user}/></>}</> : path === '/community/publishing' ? <CommunityPublishing profile={account.data?.profile || null} onProfileSaved={account.reload} startPublish={startPublish} chooseProject={chooseProject}/> : path === '/community/impact' ? <CommunityImpact/> : path === '/community/moderation' ? <CommunityModeration/> : path === '/community' || path === '/community/saved' ? <>
      <header className="community-heading"><div><p className="community-eyebrow">Made to be made your own</p><h1>{path.endsWith('/saved') ? 'Your saved designs' : 'Explore Community'}</h1><p>{path.endsWith('/saved') ? 'A private collection of ideas worth returning to.' : 'Discover useful designs, meet their makers, and start with something inspiring.'}</p></div><button className="button primary" onClick={startPublish}><Upload size={16}/> Publish to Community</button></header>
      {!path.endsWith('/saved') && <><form className="community-query" role="search" onSubmit={event => { event.preventDefault(); const query = new FormData(event.currentTarget).get('q'); filter('q', String(query || '')); }}><Search size={20}/><input key={url.searchParams.get('q')} name="q" type="search" aria-label="Search public designs" placeholder="Search designs, tags or creators" maxLength={200} defaultValue={url.searchParams.get('q') || ''}/><button className="button" type="submit">Search</button></form><div className="community-categories" aria-label="Design categories"><button className={!url.searchParams.has('kind') ? 'selected' : ''} onClick={() => filter('kind','')}>All designs</button>{communityKinds.map(([kind,label]) => <button className={url.searchParams.get('kind') === kind ? 'selected' : ''} key={kind} onClick={() => filter('kind',kind)}>{label}</button>)}</div><div className="community-toolbar"><button className="button" onClick={() => setFilterOpen(true)}><SlidersHorizontal size={16}/> Filters</button><Field label="Sort designs"><select value={url.searchParams.get('sort') || (url.searchParams.has('q') ? 'relevance' : 'trending')} onChange={event => filter('sort',event.target.value)}>{[['trending','Trending'],['newest','Newest'],['most-used','Most used · unique people'],['most-downloaded','Most downloaded · unique people'],['relevance','Relevance']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div><div className="community-tags">{['q','tags','format','period','creator','collection'].filter(key => url.searchParams.has(key)).map(key => <button key={key} onClick={() => filter(key,'')}>{key}: {url.searchParams.get(key)} <X size={12}/></button>)}</div></>}
      <CommunityBrowse query={url.search} saved={path.endsWith('/saved')} signedIn={!!user}/>
    </> : <section className="community-empty"><h1>Page not found</h1><a href="/community">Return to Explore</a></section>}
    {importOperation && <CommunityJobStatus operationId={importOperation}/>}
  </main>
  {filterOpen && <CommunityFilters params={url.searchParams} onApply={values => { const next = new URL(location.href); for (const [key,value] of Object.entries(values)) value ? next.searchParams.set(key,value) : next.searchParams.delete(key); next.searchParams.delete('cursor'); history.pushState(null,'',next.pathname+next.search); setUrl(next); setFilterOpen(false); }} onClose={() => setFilterOpen(false)}/>}
  {search.open && <CommunitySearchDialog initialScope="community" accountId={user?.id} onClose={() => search.setOpen(false)}/>}
  {picker && <CommunityProjectPicker onClose={() => setPicker(false)} choose={id => void chooseProject(id)} onImport={async file => { const body = new FormData(); body.append('file',file); const operationId = crypto.randomUUID(); if(user) storedCommunityImport(user.id, operationId); setImportOperation(operationId); body.append('operationId',operationId); const {job} = await api<{job:CommunityJob}>('/api/community/imports',{method:'POST',body}); setImportOperation(job.operationId); setPicker(false); }}/>} 
  {publishProject && <CommunityPublishDialog project={publishProject} accountId={user?.id} listing={publishListing} onClose={() => setPublishProject(null)}/>}
  </div></CommunityBookmarks>;
}
function CommunityGrid({ listings, signedIn, saved = false }: { listings: CommunityListing[]; signedIn: boolean; saved?: boolean }) { return <div className="community-grid">{listings.map(listing => <CommunityCard key={listing.id} listing={listing} signedIn={signedIn} saved={saved}/>)}</div>; }
function CommunityBrowse({ query, saved, signedIn }: { query: string; saved: boolean; signedIn: boolean }) {
  const currentQuery = useRef(query); currentQuery.current = query;
  const [listings,setListings] = useState<CommunityListing[]>([]), [cursor,setCursor] = useState<string | null>(null), [error,setError] = useState(''), [loading,setLoading] = useState(true), [more,setMore] = useState(false), [retry,setRetry] = useState(0);
  const collections = useCommunityResource<{collections:CommunityCollection[]}>(!saved && !query ? '/api/community/collections' : null);
  useEffect(() => { const controller=new AbortController(); setLoading(true);setListings([]);setError('');setCursor(null); void api<ListingsResponse>(saved ? '/api/community/me/bookmarks' : `/api/community/listings${query}`,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setListings(data.listings);setCursor(data.nextCursor||null);}}).catch(error=>{if(!controller.signal.aborted)setError(message(error));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort(); },[query,saved,retry]);
  async function loadMore() { if(!cursor)return;setMore(true);setError('');try{const params=new URLSearchParams(query);params.set('cursor',cursor);const data=await api<ListingsResponse>(`/api/community/listings?${params}`);if(currentQuery.current!==query)return;setListings(previous=>[...previous,...data.listings.filter(item=>!previous.some(old=>old.id===item.id))]);setCursor(data.nextCursor||null);}catch(error){if(error instanceof ApiError && error.code === 'cursor_reset_required')setRetry(value=>value+1);else setError(message(error));}finally{setMore(false);} }
  return <>{collections.data?.collections.filter(collection=>collection.items.some(item=>item.listing)).map(collection=><section className="community-collection" key={collection.id}><h2><a href={`/community?collection=${collection.id}`}>{collection.title}</a></h2><p>{collection.description}</p><div className="community-grid">{collection.items.filter(item=>item.listing).slice(0,3).map(item=><div key={item.listingId}><CommunityCard listing={item.listing!} signedIn={signedIn}/><p className="community-pick-reason">Community pick · {item.reason}</p></div>)}</div></section>)}
    {loading ? <div className="community-grid" aria-label="Loading designs" aria-busy="true">{[0,1,2,3,4,5].map(index=><div key={index} className="community-skeleton"/>)}</div> : <><p className="community-result-count" role="status">{listings.length} designs{cursor ? ' loaded' : ''}</p><CommunityGrid listings={listings} signedIn={signedIn} saved={saved}/>{!listings.length&&!error&&<section className="community-empty"><Globe size={30}/><h2>{saved?'Nothing saved yet':query?'No designs match these filters':'The next great starting point could be yours'}</h2><p>{saved?'Save a public design and it will appear here.':query?'Try fewer filters or a different search.':'There are no public designs yet. Publish a design to get things started.'}</p>{query&&<a href="/community" className="button">Clear filters</a>}</section>}</>}
    {error&&<section className="community-empty" role="alert"><p>{error}</p><button className="button" onClick={()=>setRetry(value=>value+1)}>Reload results</button></section>}{cursor&&<button className="button community-load-more" disabled={more} onClick={()=>void loadMore()}>{more?'Loading…':'Load more'}</button>}
  </>;
}
function CommunityFilters({params,onApply,onClose}:{params:URLSearchParams;onApply:(values:Record<string,string>)=>void;onClose:()=>void}) {
  const taxonomy=useCommunityResource<{formats:string[]}>('/api/community/taxonomy');
  return <Modal title="Filter designs" onClose={onClose}><form className="modal-body" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);onApply({tags:String(data.get('tags')||''),format:String(data.get('format')||''),period:String(data.get('period')||'')});}}><Field label="Tags" hint="Comma-separated; designs must match every tag."><input name="tags" defaultValue={params.get('tags')||''} maxLength={300}/></Field><Field label="Ready download format"><select name="format" defaultValue={params.get('format')||''}><option value="">Any format</option>{taxonomy.data?.formats.map(format=><option key={format} value={format}>{formatLabel(format)}</option>)}</select></Field><Field label="First published"><select name="period" defaultValue={params.get('period')||''}><option value="">Any time</option><option value="week">Past week</option><option value="month">Past month</option><option value="year">Past year</option></select></Field><button className="button primary">Apply filters</button></form></Modal>;
}
function CommunityPublishing({profile,onProfileSaved,startPublish,chooseProject}:{profile:CommunityProfile|null;onProfileSaved:()=>void;startPublish:()=>void;chooseProject:(id:string,listing:CommunityListing)=>void}) {
  const resource=useCommunityResource<{listings:CommunityListing[]}>('/api/community/me/listings');const [error,setError]=useState(''),[unlist,setUnlist]=useState<CommunityListing|null>(null),[busy,setBusy]=useState(false);
  return <><header className="community-heading"><div><h1>Your publishing</h1><p>Community listings and Share links are independent.</p></div><button className="button primary" onClick={startPublish}>Publish a design</button></header><details className="community-profile-settings"><summary>Edit public profile</summary><CommunityProfileForm key={profile?.revision||0} profile={profile} onSaved={onProfileSaved}/></details>{resource.loading&&<p role="status">Loading your listings…</p>}{(resource.error||error)&&<p role="alert">{resource.error||error}</p>}<div className="community-publishing-list">{resource.data?.listings.map(listing=><article key={listing.id}><div><h2>{listing.title}</h2><p>{listing.state} · Version {listing.version} · Revision {listing.revision}</p>{listing.moderationReason&&<p>{listing.moderationReason}</p>}</div><div className="button-row">{listing.state==='live'&&<a className="button" href={`/community/designs/${listing.id}`}>View</a>}{listing.sourceProjectId&&<button className="button" onClick={()=>chooseProject(listing.sourceProjectId!,listing)}>Review update</button>}{listing.state==='live'&&<button className="button" onClick={()=>setUnlist(listing)}>Unlist</button>}</div></article>)}</div>{resource.data&&!resource.data.listings.length&&<p>No listings yet. Choose a saved project to review for publication.</p>}{unlist&&<Modal title="Unlist this design?" onClose={()=>setUnlist(null)}><div className="modal-body"><p>New requests to this Community listing, preview and downloads will stop working. Existing private remixes and files already downloaded remain available. Your old Share link is unaffected.</p><button className="button danger" disabled={busy} onClick={()=>{setBusy(true);void post(`/api/community/listings/${unlist.id}/unlist`,{expectedListingRevision:unlist.revision,operationId:crypto.randomUUID()}).then(()=>{setUnlist(null);resource.reload();}).catch(error=>setError(message(error))).finally(()=>setBusy(false));}}>Unlist design</button></div></Modal>}</>;
}
function CommunityProjectPicker({onClose,choose,onImport}:{onClose:()=>void;choose:(id:string)=>void;onImport:(file:File)=>Promise<void>}) {
  const [query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const resource=useCommunityResource<{projects:Project[]}>(`/api/projects?q=${encodeURIComponent(query)}&limit=48`);
  return <Modal title="Choose a saved project" onClose={onClose}><div className="modal-body"><Field label="Find your project"><input value={query} maxLength={200} onChange={event=>setQuery(event.target.value)}/></Field><p>Publication starts from the latest saved revision. You review public content before confirming.</p>{resource.loading&&<p role="status">Loading projects…</p>}{resource.error&&<p role="alert">{resource.error}</p>}<ul className="community-project-list">{resource.data?.projects.map(project=><li key={project.id}><button className="button" onClick={()=>choose(project.id)}>{project.name}</button></li>)}</ul><Field label="Import a Studio project package" hint="Imports are private and validate all bundled assets. External attribution remains declared unless verified by the server."><input type="file" accept=".zip,application/zip" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file){setBusy(true);void onImport(file).catch(error=>setError(message(error))).finally(()=>setBusy(false));}}}/></Field>{error&&<p role="alert">{error}</p>}</div></Modal>;
}
