import { useState } from 'react';
import type { CommunityCollection, CommunityFile } from '../shared/community';
import { post, put, message } from './api';
import { Field, Modal } from './ui';
import { useCommunityResource } from './community-client';
type Report = { id: string; listingId: string; version: number; versionChecksum?: string; reason: string; message: string; status: string; revision: number; listingRevision: number; createdAt: string; previewUrl?: string | null; files?: CommunityFile[]; history?: { action: string; reason: string; createdAt: string }[] };
export function CommunityModeration() {
  const reports=useCommunityResource<{reports:Report[]}>('/api/community/moderation/reports');
  const collections=useCommunityResource<{collections:CommunityCollection[]}>('/api/community/moderation/collections');
  const [selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<CommunityCollection|null|undefined>(undefined);
  return <section><header className="community-heading"><div><h1>Community moderation</h1><p>Private reports and reviewed curation. Every decision requires a reason.</p></div><button className="button" onClick={()=>setEditing(null)}>Create collection</button></header>{reports.loading&&<p role="status">Loading reports…</p>}{reports.error&&<p role="alert">{reports.error}</p>}<h2>Report queue</h2><div className="community-publishing-list">{reports.data?.reports.map(report=><article key={report.id}><div><strong>{report.reason}</strong><p>Version {report.version} · {report.status} · {new Date(report.createdAt).toLocaleDateString()}</p></div><button className="button" onClick={()=>setSelected(report.id)}>Review report</button></article>)}</div>{reports.data&&!reports.data.reports.length&&<p>No reports to review.</p>}<h2>Curated collections</h2>{collections.data?.collections.map(collection=><article className="community-collection" key={collection.id}><h3>{collection.title}</h3><p>{collection.description}</p><p>{collection.items.length} reviewed items · Revision {collection.revision}</p><button className="button" onClick={()=>setEditing(collection)}>Edit collection and order</button></article>)}{selected&&<ReportReview id={selected} onClose={()=>setSelected(null)} onResolved={()=>{setSelected(null);reports.reload();}}/>}{editing!==undefined&&<CollectionEditor collection={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);collections.reload();}}/>}</section>;
}
function ReportReview({id,onClose,onResolved}:{id:string;onClose:()=>void;onResolved:()=>void}) {
  const resource=useCommunityResource<{report:Report}>(`/api/community/moderation/reports/${encodeURIComponent(id)}`);
  const [action,setAction]=useState('dismiss'),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false);
  return <Modal title="Review reported content" onClose={onClose} wide><div className="modal-body">{resource.loading&&<p role="status">Loading report…</p>}{resource.error&&<p role="alert">{resource.error}</p>}{resource.data&&<><p><strong>{resource.data.report.reason}</strong> · Version {resource.data.report.version} · {resource.data.report.status}</p><p className="community-description">{resource.data.report.message}</p><p className="community-checksum">Evidence checksum: {resource.data.report.versionChecksum||'Unavailable'}</p>{resource.data.report.previewUrl?<><button className="button" onClick={()=>setPreview(!preview)}>{preview?'Stop preview':'Preview reported version'}</button>{preview&&<iframe className="community-moderator-preview" title="Private reported version preview" sandbox="allow-scripts" src={resource.data.report.previewUrl}/>}</>:<p>Content unavailable. The version has been purged or is no longer retained; only minimal report evidence remains.</p>}<h3>Decision history</h3>{resource.data.report.history?.map((item,index)=><p key={index}>{item.action} · {item.reason} · {new Date(item.createdAt).toLocaleString()}</p>)}<form onSubmit={event=>{event.preventDefault();setBusy(true);setError('');void post(`/api/community/moderation/reports/${id}/resolve`,{operationId:crypto.randomUUID(),expectedReportRevision:resource.data!.report.revision,expectedListingRevision:resource.data!.report.listingRevision,action,reason}).then(onResolved).catch(error=>setError(message(error))).finally(()=>setBusy(false));}}><Field label="Decision"><select value={action} onChange={event=>setAction(event.target.value)}><option value="dismiss">Dismiss report</option><option value="hide">Hide public listing</option><option value="restore">Restore moderator visibility</option></select></Field><p>Restore never overrides owner unlisting or source deletion. Hide prevents new public preview and file requests.</p><Field label="Decision reason"><textarea required maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></Field>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}>Confirm decision</button></form></>}</div></Modal>;
}
function CollectionEditor({collection,onClose,onSaved}:{collection:CommunityCollection|null;onClose:()=>void;onSaved:()=>void}) {
  const [title,setTitle]=useState(collection?.title||''),[description,setDescription]=useState(collection?.description||''),[items,setItems]=useState(collection?.items.map(({listingId,version,reason})=>({listingId,version,reason}))||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const edit=(index:number,changes:Partial<(typeof items)[number]>)=>setItems(values=>values.map((item,position)=>position===index?{...item,...changes}:item));
  return <Modal title={collection?'Edit collection':'Create collection'} onClose={onClose} wide><form className="modal-body" onSubmit={event=>{event.preventDefault();setBusy(true);setError('');const body={title,description,items,expectedCollectionRevision:collection?.revision||0};void (collection?put(`/api/community/moderation/collections/${collection.id}`,body):post('/api/community/moderation/collections',body)).then(onSaved).catch(error=>setError(message(error))).finally(()=>setBusy(false));}}><Field label="Collection title"><input required maxLength={120} value={title} onChange={event=>setTitle(event.target.value)}/></Field><Field label="Collection description"><textarea maxLength={1000} value={description} onChange={event=>setDescription(event.target.value)}/></Field><p>Only real live designs at the reviewed version appear publicly. A later release requires a new review. Remove all items to leave an empty collection.</p>{items.map((item,index)=><fieldset key={index}><legend>Position {index+1}</legend><Field label="Listing ID"><input required value={item.listingId} onChange={event=>edit(index,{listingId:event.target.value})}/></Field><Field label="Reviewed version"><input required type="number" min={1} value={item.version} onChange={event=>edit(index,{version:Number(event.target.value)})}/></Field><Field label="Why this is a Community pick"><input required maxLength={500} value={item.reason} onChange={event=>edit(index,{reason:event.target.value})}/></Field><div className="button-row"><button type="button" className="button" disabled={index===0} onClick={()=>setItems(values=>{const next=[...values];[next[index-1],next[index]]=[next[index],next[index-1]];return next;})}>Move up</button><button type="button" className="button" onClick={()=>setItems(values=>values.filter((_,position)=>position!==index))}>Remove</button></div></fieldset>)}<button type="button" className="button" disabled={items.length>=100} onClick={()=>setItems(values=>[...values,{listingId:'',version:1,reason:''}])}>Add reviewed design</button>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}>Save collection</button></form></Modal>;
}
