import {MotionCurveHandles} from './motion-curve-handles';
import {bakeMotion} from '../shared/motion-bake';
import {useState} from 'react';
import {uid} from '../shared/schema';
import type {Character,MotionChannel,MotionKey} from '../shared/character-schema';
import {newClip,retimeKeys} from '../shared/character-editing';
import {sampleChannel} from '../shared/motion-channels';
export function MotionClipPanel({c,clipId,choose,time,seek,edit}:{c:Character;clipId:string;choose:(id:string)=>void;time:number;seek:(n:number)=>void;edit:(fn:(c:Character)=>void)=>void}){
 const clip=c.clips.find(x=>x.id===clipId),[channelId,setChannel]=useState(''),[selected,setSelected]=useState<string[]>([]),[offset,setOffset]=useState(.1),[scale,setScale]=useState(1),[copy,setCopy]=useState(false),[value,setValue]=useState('0'),[property,setProperty]=useState<MotionChannel['property']>('rotation'),[target,setTarget]=useState('');
 const channel=clip?.channels.find(x=>x.id===channelId)??clip?.channels[0];
 const update=(fn:(ch:MotionChannel)=>void)=>edit(c=>fn(c.clips.find(x=>x.id===clipId)!.channels.find(x=>x.id===channel!.id)!));
 const values=channel?.keys.flatMap(k=>typeof k.value==='number'?[k.value]:[])??[],min=Math.min(0,...values),max=Math.max(1,...values),y=(v:number)=>110-(v-min)/(max-min)*100;
 return <section aria-label="Animation clips"><button onClick={()=>{const clip=newClip();edit(c=>c.clips.push(clip));choose(clip.id);}}>New clip</button>
 <label>Clip<select value={clipId} onChange={e=>{choose(e.target.value);setSelected([]);}}><option value="">Choose clip</option>{c.clips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {clip&&<><button onClick={()=>{const id=uid();edit(c=>c.clips.push(bakeMotion(c,clipId,id,clip.name+' baked',12)));choose(id);}}>Bake constraints to new clip (12 fps)</button><label>Clip name<input value={clip.name} onChange={e=>edit(c=>{c.clips.find(x=>x.id===clipId)!.name=e.target.value;})}/></label><label>Duration<input type="number" min=".01" step=".1" value={clip.duration} onChange={e=>edit(c=>{c.clips.find(x=>x.id===clipId)!.duration=e.target.valueAsNumber;})}/></label><label><input type="checkbox" checked={clip.loop} onChange={e=>edit(c=>{c.clips.find(x=>x.id===clipId)!.loop=e.target.checked;})}/>Loop</label>
 <label>Clip time<input aria-label="Clip time" type="range" min="0" max={clip.duration} step=".01" value={time} onChange={e=>seek(e.target.valueAsNumber)}/><input aria-label="Clip time seconds" type="number" min="0" max={clip.duration} step=".01" value={time} onChange={e=>seek(Math.max(0,Math.min(clip.duration,e.target.valueAsNumber||0)))}/></label>
 <label>Channel<select value={channel?.id??''} onChange={e=>{setChannel(e.target.value);setSelected([]);}}>{clip.channels.map(ch=><option key={ch.id} value={ch.id}>{ch.targetId} · {ch.property}</option>)}</select></label>
 <details><summary>Add property channel</summary><select aria-label="Channel target" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Target</option>{(['bones','slots','attachments','constraints'] as const).flatMap(collection=>c[collection].map(x=><option key={x.id} value={`${collection}:${x.id}`}>{x.name} ({collection})</option>))}</select><select aria-label="Channel property" value={property} onChange={e=>setProperty(e.target.value as MotionChannel['property'])}>{['x','y','rotation','scaleX','scaleY','opacity','attachment','order','deform','mix','targetX','targetY','position','value'].map(p=><option key={p}>{p}</option>)}</select><button disabled={!target} onClick={()=>{const [collection,id]=target.split(':'),a=c.attachments.find(x=>x.id===id),mesh=a?.mesh??c.attachments.find(x=>x.id===a?.sourceMeshId)?.mesh,ch:MotionChannel={id:uid(),target:({bones:'bone',slots:'slot',attachments:'attachment',constraints:'constraint'} as const)[collection as 'bones'],targetId:id,property,keys:[],...(property==='deform'?{meshVersion:mesh?.version}: {})};edit(c=>c.clips.find(x=>x.id===clipId)!.channels.push(ch));setChannel(ch.id);}}>Add channel</button></details>
 {channel&&<><label><input type="checkbox" checked={channel.muted??false} onChange={e=>update(ch=>{ch.muted=e.target.checked;})}/>Mute</label><label><input type="checkbox" checked={channel.locked??false} onChange={e=>update(ch=>{ch.locked=e.target.checked;})}/>Lock</label>
 <svg viewBox="0 0 320 125" aria-label="Property curve" style={{width:'100%',background:'#eef2ff'}} onClick={e=>{const box=e.currentTarget.getBoundingClientRect();seek((e.clientX-box.left)/box.width*clip.duration);}}><path fill="none" stroke="#7c3aed" strokeWidth="2" d={Array.from({length:121},(_,n)=>{const v=sampleChannel(channel,n/120*clip.duration);return `${n?'L':'M'}${n/120*320},${y(typeof v==='number'?v:0)}`;}).join(' ')}/>{channel.keys.map(k=><circle key={k.id} cx={k.time/clip.duration*320} cy={y(typeof k.value==='number'?k.value:0)} r="4" fill={selected.includes(k.id)?'#dc2626':'#4f46e5'}/>)}</svg>
 <label>New value (number, attachment ID, or deformation array)<input value={value} onChange={e=>setValue(e.target.value)}/></label><button disabled={channel.locked} onClick={()=>update(ch=>{let parsed:MotionKey['value'];try{parsed=JSON.parse(value);}catch{parsed=value;}if(ch.keys.some(k=>k.time===time))throw new Error('A key already exists at this time. Edit that key instead.');ch.keys.push({id:uid(),time,value:parsed});})}>Add property key</button>
 <div style={{maxHeight:220,overflow:'auto'}}>{channel.keys.map(k=><div key={k.id} className="motion-key-row"><input aria-label={`Select key ${k.time}`} type="checkbox" checked={selected.includes(k.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,k.id]:s.filter(id=>id!==k.id))}/><button onClick={()=>seek(k.time)}>{k.time.toFixed(2)}s</button><input aria-label={`Value at ${k.time}`} disabled={channel.locked} defaultValue={typeof k.value==='string'?k.value:JSON.stringify(k.value)} onBlur={e=>update(ch=>{let v:MotionKey['value'];try{v=JSON.parse(e.target.value);}catch{v=e.target.value;}ch.keys.find(x=>x.id===k.id)!.value=v;})}/><select aria-label={`Easing at ${k.time}`} disabled={channel.locked} value={Array.isArray(k.easing)?'custom':k.easing??'linear'} onChange={e=>update(ch=>{ch.keys.find(x=>x.id===k.id)!.easing=e.target.value==='custom'?[.25,.1,.25,1]:e.target.value as 'linear';})}>{['linear','easeIn','easeOut','easeInOut','step','bounce','spring','custom'].map(x=><option key={x}>{x}</option>)}</select>{Array.isArray(k.easing)&&<MotionCurveHandles value={k.easing} disabled={channel.locked} change={value=>update(ch=>{ch.keys.find(x=>x.id===k.id)!.easing=value;})}/>} {Array.isArray(k.easing)&&k.easing.map((v,j)=><input key={j} aria-label={`Bezier ${j+1} at ${k.time}`} type="number" step=".05" value={v} disabled={channel.locked} onChange={e=>update(ch=>{const key=ch.keys.find(x=>x.id===k.id)!;if(Array.isArray(key.easing))key.easing[j]=e.target.valueAsNumber;})}/>)}</div>)}</div>
 <label>Offset seconds<input type="number" step=".01" value={offset} onChange={e=>setOffset(e.target.valueAsNumber)}/></label><label>Time scale<input type="number" min=".01" step=".1" value={scale} onChange={e=>setScale(e.target.valueAsNumber)}/></label><label><input type="checkbox" checked={copy} onChange={e=>setCopy(e.target.checked)}/>Copy selected keys</label><button disabled={!selected.length||channel.locked} onClick={()=>update(ch=>{ch.keys=retimeKeys(ch.keys,new Set(selected),offset,scale,time,clip.duration,copy);})}>Apply key timing</button><button disabled={!selected.length||channel.locked} onClick={()=>update(ch=>{ch.keys=ch.keys.filter(k=>!selected.includes(k.id));})}>Delete selected keys</button>
 </>}
 <details><summary>Clip events</summary><input placeholder="Event name" aria-label="New event name" onKeyDown={e=>{if(e.key==='Enter'&&e.currentTarget.value){const name=e.currentTarget.value;edit(c=>c.clips.find(x=>x.id===clipId)!.events.push({id:uid(),name,time}));e.currentTarget.value='';}}}/>{clip.events.map(event=><div key={event.id}>{event.time}s · {event.name}<button onClick={()=>edit(c=>{const clip=c.clips.find(x=>x.id===clipId)!;clip.events=clip.events.filter(x=>x.id!==event.id);})}>Remove event</button></div>)}</details>
 </>}
 </section>;
}
