export function ObservabilityDocumentation() {
  return <><p>Open <a href="/activity">Activity & usage</a> to inspect your account’s request log, provider measurements and correlated traces. Templates and design systems have stable links at <a href="/templates">/templates</a> and <a href="/design-systems">/design-systems</a>; opening these pages does not create or modify a project.</p>
    <h2>Find a failed action</h2><ol><li>Choose a period, channel, operation kind or status. Project IDs narrow the view to a saved design.</li><li>Open a trace from the log, or paste the request ID shown in an API error. Instrumented responses return <code>X-Request-ID</code>.</li><li>Inspect HTTP, MCP tool, provider and export steps. A provider success can be followed by a document validation failure; reported usage remains visible.</li><li>Fix the diagnostic code or conflict before retrying. A running operation is different from a recently active account. Stale operations become interrupted/unknown.</li></ol>
    <h2>Usage without invented numbers</h2><p>Input/output tokens and USD costs come from explicit provider response fields. “Not reported” means unavailable, not zero. Coverage shows how many calls have measurements; sums may be partial. Media polling does not count as another generation. Latency and failure rates help identify slow or unreliable actions; they do not measure design quality.</p>
    <h2>Agent access</h2><pre><code>{'dsa observability summary --days 7\ndsa observability events --status error --limit 25\ndsa observability trace REQUEST_ID --days 30'}</code></pre><p>REST uses <code>GET /api/observability/summary</code>, <code>GET /api/observability/events</code>, and <code>GET /api/observability/trace/:id</code>. Network MCP tools are <code>get_observability_summary</code>, <code>list_activity_events</code>, and <code>get_activity_trace</code>. Browser WebMCP exposes <code>studio_api_get_observability_summary</code>, <code>studio_api_get_observability_events</code>, and <code>studio_api_get_observability_trace_id</code>. All use the same server authorization.</p>
    <h2>Privacy and operator access</h2><p>The default <code>scope=owner</code> shows your account. All-account inspection requires an account ID explicitly listed in server <code>OBSERVABILITY_ADMIN_IDS</code> plus session or API-key authentication. MCP OAuth cannot use <code>scope=all</code>. Logs retain safe metadata for 30 days; they exclude prompts, design text, raw exception messages, credentials and arbitrary URLs.</p>
    <h2>PostHog and coverage</h2><p>First-party browser events use the strict schema on <code>POST /api/observability/client-events</code>. Optional PostHog forwarding requires <code>POSTHOG_PROJECT_KEY</code> and the project’s verified <code>POSTHOG_HOST</code>. Cloud hosts are <code>https://us.i.posthog.com</code> and <code>https://eu.i.posthog.com</code>. No DOM autocapture, session replay or email identification is enabled. This follows the <a href="https://posthog.com/docs/api/capture" target="_blank" rel="noreferrer">PostHog capture API</a>.</p><p>Coverage reports storage state, dropped writes and PostHog delivery failures. Runtime health counters reset when an instance restarts and do not represent a global durable outage history. Tracking failure never retries a billed design operation.</p>
    <h2>Editor controls</h2><p>Shift-click canvas objects or layers to build a selection. Use the editor’s keyboard-shortcut help for select all, duplicate, grouping, undo/redo, delete and coarse/fine nudging. Text editing preserves canvas typography; font search previews the visible families. Install the complete <code>skills/design-studio-ai</code> directory, including its design-kind references, so agents use the matching layout and quality guidance.</p>
  </>;
}
