import { reorderPaintingGroup } from '../shared/painting-layer-operations';
import type { Painting } from '../shared/painting-schema';
import { uid } from '../shared/schema';

export function PaintingAdvancedControls({ painting, layerId, disabled, onEdit }: { painting: Painting; layerId: string; disabled: boolean; onEdit: (edit: (next: Painting) => void) => void }) {
  const layer = painting.layers.find(l => l.id === layerId); if (!layer) return null;
  const moveGroup = (id: string, direction: number) => onEdit(next => reorderPaintingGroup(next, id, next.groups.findIndex(g => g.id === id) + direction));
  return <fieldset disabled={disabled}><legend>Canvas, groups and masks</legend>
    <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget), width = Number(data.get('width')), height = Number(data.get('height')); onEdit(next => { if (next.layers.some(l => l.locked) || next.groups.some(g => 'locked' in g && g.locked === true)) throw new Error('Unlock layers before resizing the canvas.'); next.width = width; next.height = height; for (const l of next.layers) { l.tiles = l.tiles.filter(t => t.x * 512 < width && t.y * 512 < height); if (l.mask) l.mask.tiles = l.mask.tiles.filter(t => t.x * 512 < width && t.y * 512 < height); } }); }}>
      <label>Width<input key={`w${painting.width}`} name="width" aria-label="Painting width" type="number" min="1" max="4096" required defaultValue={painting.width}/></label><label>Height<input key={`h${painting.height}`} name="height" aria-label="Painting height" type="number" min="1" max="4096" required defaultValue={painting.height}/></label><button>Resize canvas</button><small>Anchor: top left. Cropped tiles are removed.</small>
    </form>
    <label>Layer group<select aria-label="Layer group" value={layer.groupId ?? ''} disabled={layer.locked} onChange={e => { const groupId = e.currentTarget.value || undefined; onEdit(next => { next.layers.find(l => l.id === layerId)!.groupId = groupId; }); }}><option value="">No group</option>{painting.groups.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
    <button disabled={painting.groups.length >= 24} onClick={() => onEdit(next => { next.groups.push({ id: uid(), name: `Group ${next.groups.length + 1}`, opacity: 1, visible: true }); })}>Add group</button>
    {painting.groups.map(group => <div key={group.id}><input aria-label={`Name ${group.name}`} defaultValue={group.name} maxLength={200} onBlur={e => { const name = e.target.value.trim(); if (name && name !== group.name) onEdit(next => { next.groups.find(g => g.id === group.id)!.name = name; }); }}/><label><input type="checkbox" checked={group.visible} onChange={e => { const visible = e.currentTarget.checked; onEdit(next => { next.groups.find(g => g.id === group.id)!.visible = visible; }); }}/>Show group</label><label><input type="checkbox" checked={'locked' in group && group.locked === true} onChange={e => { const locked = e.currentTarget.checked; onEdit(next => { next.groups.find(g => g.id === group.id)!.locked = locked; }); }}/>Lock group</label><label>Group opacity<input type="number" aria-label={`${group.name} opacity`} min="0" max="1" step=".05" defaultValue={group.opacity} key={group.opacity} onBlur={e => { const opacity = Number(e.target.value); if (opacity >= 0 && opacity <= 1 && opacity !== group.opacity) onEdit(next => { next.groups.find(g => g.id === group.id)!.opacity = opacity; }); }}/></label><button disabled={group.locked || painting.groups[0].id === group.id} onClick={() => moveGroup(group.id, -1)}>Group down</button><button disabled={group.locked || painting.groups.at(-1)?.id === group.id} onClick={() => moveGroup(group.id, 1)}>Group up</button><button onClick={() => onEdit(next => { next.groups = next.groups.filter(g => g.id !== group.id); next.layers.forEach(l => { if (l.groupId === group.id) delete l.groupId; }); })}>Ungroup</button></div>)}
    <button disabled={layer.locked} onClick={() => onEdit(next => { const current = next.layers.find(l => l.id === layerId)!; current.mask = { enabled: true, tiles: structuredClone(current.tiles) }; })}>Mask from layer alpha</button>
    {layer.mask && <><label><input type="checkbox" checked={layer.mask.enabled} disabled={layer.locked} onChange={e => { const enabled = e.currentTarget.checked; onEdit(next => { next.layers.find(l => l.id === layerId)!.mask!.enabled = enabled; }); }}/>Enable mask</label><button disabled={layer.locked} onClick={() => onEdit(next => { delete next.layers.find(l => l.id === layerId)!.mask; })}>Remove mask</button></>}
  </fieldset>;
}
