import type { Painting, PaintLayer } from '../shared/painting-schema';
import { uid } from '../shared/schema';
export function PaintLayerControls({ painting, layerId, disabled, onEdit }: { painting: Painting; layerId: string; disabled: boolean; onEdit: (edit: (next: Painting) => void) => void }) {
  const layer = painting.layers.find(l => l.id === layerId); if (!layer) return null;
  const patch = (changes: Partial<PaintLayer>) => onEdit(next => Object.assign(next.layers.find(l => l.id === layerId)!, changes));
  return <div className="paint-layer-properties">
    <label>Layer name<input aria-label="Paint layer name" key={layer.name} defaultValue={layer.name} disabled={disabled} maxLength={200} onBlur={e => { if (e.target.value.trim() && e.target.value !== layer.name) patch({ name: e.target.value.trim() }); else e.target.value = layer.name; }}/></label>
    <label>Opacity<input aria-label="Layer opacity" key={layer.opacity} type="range" min="0" max="1" step=".05" defaultValue={layer.opacity} disabled={disabled} onPointerUp={e => { const opacity = Number(e.currentTarget.value); if (opacity !== layer.opacity) patch({ opacity }); }} onKeyUp={e => { const opacity = Number(e.currentTarget.value); if (opacity !== layer.opacity) patch({ opacity }); }}/></label>
    <label>Blend<select aria-label="Layer blend" value={layer.blend} disabled={disabled} onChange={e => patch({ blend: e.target.value as PaintLayer['blend'] })}>{['normal', 'multiply', 'screen', 'overlay'].map(mode => <option key={mode}>{mode}</option>)}</select></label>
    <label><input aria-label="Alpha lock" type="checkbox" checked={layer.alphaLock} disabled={disabled} onChange={e => patch({ alphaLock: e.target.checked })}/> Alpha lock</label>
    <label><input aria-label="Clip to layer below" type="checkbox" checked={layer.clipping} disabled={disabled || painting.layers[0].id === layerId} onChange={e => patch({ clipping: e.target.checked })}/> Clip to layer below</label>
    <div className="paint-layer-actions"><button disabled={disabled || painting.layers.at(-1)?.id === layerId} onClick={() => onEdit(next => { const i = next.layers.findIndex(l => l.id === layerId); [next.layers[i], next.layers[i + 1]] = [next.layers[i + 1], next.layers[i]]; next.layers[0].clipping = false; })}>Move up</button><button disabled={disabled || painting.layers[0].id === layerId} onClick={() => onEdit(next => { const i = next.layers.findIndex(l => l.id === layerId); [next.layers[i], next.layers[i - 1]] = [next.layers[i - 1], next.layers[i]]; next.layers[0].clipping = false; })}>Move down</button><button disabled={disabled || painting.layers.length >= 24} onClick={() => onEdit(next => { const copy = structuredClone(layer); copy.id = uid(); copy.name = `${layer.name.slice(0, 190)} copy`; next.layers.splice(next.layers.findIndex(l => l.id === layerId) + 1, 0, copy); })}>Duplicate</button><button disabled={disabled || layer.locked || painting.layers.length === 1} onClick={() => onEdit(next => { next.layers = next.layers.filter(l => l.id !== layerId); next.layers[0].clipping = false; })}>Delete layer</button></div>
  </div>;
}
