import {SceneTextureEditor} from './scene-texture-editor';
import {SceneAdvancedTools,type SceneBrushTool} from './scene-advanced-tools';
import {SceneClipEditor} from './scene-clip-editor';
import {rigOwner} from '../shared/scene-shared-rig';
import { sceneDocumentCommand } from './scene-document-command';
import { useState, useRef, useEffect } from 'react';
import { mutateDocument } from '../shared/operations';
import type { DesignDocument } from '../shared/schema';
import { wingedLandmarksSchema, type SceneCommand } from '../shared/scene-authoring-schema';
import { inspectScene } from '../shared/scene-inspection';
export function SceneAuthoringPanel({doc,pageId,nodeId,onDocument,selection,onHeat,onTool,onJoint,onIssue}:{doc:DesignDocument;pageId:string;nodeId?:string;onDocument:(doc:DesignDocument)=>void;selection:number[];onHeat:(bone:number|null)=>void;onTool:(tool:SceneBrushTool)=>void;onJoint:(bone:number,mode:'rest'|'pose')=>void;onIssue:(id:string,vertices:number[],time:number)=>void}){
  const page=doc.pages.find(p=>p.id===pageId)!,node=page.nodes.find(n=>n.id===nodeId),bones=node?rigOwner(node,doc).scene?.bones??[]:[];
  const [error,setError]=useState(''),[report,setReport]=useState(''),[sources,setSources]=useState<string[]>([]),[resolution,setResolution]=useState(28),[symmetry,setSymmetry]=useState(true),[rigSource,setRigSource]=useState(''),[bone,setBone]=useState('head'),[vector,setVector]=useState<[number,number,number]>([0,0,0]),[color,setColor]=useState('#ed9294'),[radius,setRadius]=useState(.08),[name,setName]=useState('blink'),[pending,setPending]=useState<DesignDocument|null>(null),[base,setBase]=useState<DesignDocument|null>(null),[rings,setRings]=useState('0,0,0,0.2\n0,0.5,0,0.25\n0,1,0,0.15');
  const latest=useRef(doc);latest.current=doc;const [busy,setBusy]=useState(false);
  const [landmarks,setLandmarks]=useState<Record<string,[number,number,number]>>({}),[landmark,setLandmark]=useState('hips'),[fingerCount,setFingerCount]=useState(3),[minimum,setMinimum]=useState<[number,number,number]>([-180,-180,-180]),[maximum,setMaximum]=useState<[number,number,number]>([180,180,180]),[mirrorBone,setMirrorBone]=useState(''),[duration,setDuration]=useState(2),[strength,setStrength]=useState(1),[wristLag,setWristLag]=useState(.15);
  useEffect(()=>{setLandmarks({});setLandmark('hips');setMirrorBone('');setMinimum([-180,-180,-180]);setMaximum([180,180,180]);},[nodeId]);
  const landmarkNames=['hips','chest','head','frontLeft','frontRight','backLeft','backRight','tail','jaw','jawTip',...['Left','Right'].flatMap(side=>['shoulder','elbow','wrist',...Array.from({length:fingerCount},(_,i)=>[`finger${i+1}Base`,`finger${i+1}Tip`]).flat()].map(joint=>`wing${side}.${joint}`))];
  const createCreature=()=>{try{const wing=(side:string)=>({shoulder:landmarks[`wing${side}.shoulder`],elbow:landmarks[`wing${side}.elbow`],wrist:landmarks[`wing${side}.wrist`],fingers:Array.from({length:fingerCount},(_,i)=>({base:landmarks[`wing${side}.finger${i+1}Base`],tip:landmarks[`wing${side}.finger${i+1}Tip`]}))});run({action:'rig-winged-quadruped',nodeId:nodeId!,landmarks:wingedLandmarksSchema.parse({...landmarks,wingLeft:wing('Left'),wingRight:wing('Right')})});}catch(e){setError((e as Error).message);}};
  const run=async(command:SceneCommand,preview=false)=>{if(busy)return;setBusy(true);try{const next=await sceneDocumentCommand(doc,pageId,command);if(latest.current!==doc)throw new Error('Design changed during processing. Run again.');setError('');if(preview){setPending(next);setBase(doc);setReport(inspectScene(next,pageId).pages[0].nodes.filter(n=>'vertices' in n).map(n=>`${n.name}: ${'vertices' in n?n.vertices:0} vertices. ${n.issues.join('; ')||'No mesh issues detected.'}`).join('\n'));}else{onDocument(next);setPending(null);setReport('Applied. Use Undo to restore the previous design.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const check=()=>{try{const output=inspectScene(doc,pageId);setReport(output.pages[0].nodes.filter(n=>!nodeId||n.id===nodeId).map(n=>`${n.name}: ${'vertices' in n?n.vertices:0} vertices, ${'triangles' in n?n.triangles:0} triangles\n${n.issues.length?n.issues.join('\n'):'No topology or weight issues detected. Inspect motion visually.'}`).join('\n\n'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className="scene-authoring-panel" aria-label="3D character authoring"><h3>Character authoring</h3>{busy&&<p role="status">Processing geometry…</p>}<p>Mesh → rig → weights → motion. Changes support Undo.</p>
    <details><summary>Surface & topology</summary><p>Remesh unrigged document geometry into a continuous surface. Source objects are kept hidden.</p><div className="scene-source-list">{page.nodes.filter(n=>n.type==='model3d'&&!n.src&&!n.parentId&&!n.scene?.bones?.length).map(n=><label key={n.id}><input type="checkbox" checked={sources.includes(n.id)} onChange={e=>setSources(e.target.checked?[...sources,n.id]:sources.filter(id=>id!==n.id))}/>{n.name}</label>)}</div><label>Resolution<input aria-label="Remesh resolution" type="number" min={12} max={48} value={resolution} onChange={e=>setResolution(+e.target.value)}/></label><label><input type="checkbox" checked={symmetry} onChange={e=>setSymmetry(e.target.checked)}/>Mirror across X</label><button disabled={!sources.length} onClick={()=>run({action:'remesh',nodeIds:sources,outputId:`surface-${Date.now()}`,resolution,symmetry,blend:.12},true)}>Preview remesh diagnostics</button>
      <label>Joint rings (x, y, z, radius per line)<textarea aria-label="Joint rings" value={rings} onChange={e=>setRings(e.target.value)}/></label><button onClick={()=>{try{run({action:'loft',outputId:`limb-${Date.now()}`,segments:16,color,rings:rings.trim().split('\n').map(line=>{const a=line.split(',').map(Number);if(a.length!==4)throw new Error('Each ring needs x, y, z, radius');return {center:a.slice(0,3) as [number,number,number],radius:a[3]};})});}catch(e){setError((e as Error).message);}}}>Build joint topology</button>
      {nodeId&&<><button onClick={()=>run({action:'convert',nodeId})}>Convert selected primitive</button><button onClick={()=>run({action:'relax',nodeId,iterations:3,strength:.2})}>Relax unbound mesh</button></>}
    </details>
    {nodeId&&<><details open><summary>Skeleton & deformation</summary><button disabled={!bones.length} onClick={()=>run({action:'share-rig',nodeId:nodeId!})}>Share skeleton with attachments</button><button onClick={()=>run({action:'rig-quadruped',nodeId})}>Create quadruped rig</button><button disabled={!bones.length} onClick={()=>run({action:'bind',nodeId,smooth:2})}>Auto-bind weights</button>
      <details><summary>Winged creature landmarks</summary><p>Place joints in mesh-local coordinates using XYZ below, or select mesh vertices to locate a joint. All landmarks are explicit. Bind the continuous body and wing surface after creating the rig.</p><label>Fingers per wing<select value={fingerCount} onChange={e=>setFingerCount(+e.target.value)}>{[3,4,5].map(count=><option key={count}>{count}</option>)}</select></label><label>Landmark<select value={landmark} onChange={e=>{setLandmark(e.target.value);if(landmarks[e.target.value])setVector(landmarks[e.target.value]);}}>{landmarkNames.map(key=><option key={key} value={key}>{key}{landmarks[key]?' ✓':''}</option>)}</select></label><button onClick={()=>setLandmarks({...landmarks,[landmark]:[...vector]})}>Set landmark from XYZ</button><button disabled={!selection.length||!node?.scene?.mesh} onClick={()=>{const positions=node!.scene!.mesh!.positions,points=selection.filter(i=>i>=0&&i<positions.length/3);if(!points.length)return;const point=[0,1,2].map(axis=>points.reduce((sum,i)=>sum+positions[i*3+axis],0)/points.length) as [number,number,number];setVector(point);setLandmarks({...landmarks,[landmark]:point});}}>Set landmark from selected vertices</button><p>{landmarkNames.filter(key=>landmarks[key]).length} / {landmarkNames.length} joints placed</p><button disabled={busy||bones.length>0||landmarkNames.some(key=>!landmarks[key])} onClick={createCreature}>Create winged quadruped rig</button></details>
      <label>Attach to rig<select value={rigSource} onChange={e=>setRigSource(e.target.value)}><option value="">Choose rig</option>{page.nodes.filter(n=>n.id!==nodeId&&n.scene?.bones?.length).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Attachment bone<input value={bone} onChange={e=>setBone(e.target.value)}/></label><button disabled={!rigSource} onClick={()=>run({action:'attach',nodeId,rigNodeId:rigSource,bone})}>Attach rigid accessory</button><label>Bone<select value={bone} onChange={e=>setBone(e.target.value)}>{bones.map(b=><option key={b.name}>{b.name}</option>)}</select></label><button disabled={!bones.length} onClick={()=>onHeat(bones.findIndex(b=>b.name===bone))}>Show weight heatmap</button><button onClick={()=>onHeat(null)}>Show material</button>
      {(['normalize','smooth','mirror'] as const).map(mode=><button key={mode} onClick={()=>run({action:'weights',nodeId,mode,iterations:2})}>{mode} weights</button>)}
      <fieldset><legend>Rotation / IK target XYZ</legend>{vector.map((v,i)=><input key={i} aria-label={`Pose ${'XYZ'[i]}`} type="number" value={v} step={.1} onChange={e=>setVector(vector.map((x,j)=>i===j?+e.target.value:x) as [number,number,number])}/>)}</fieldset><button onClick={()=>run({action:'pose',nodeId,bone,rotation:vector})}>Apply FK rotation (degrees)</button><button onClick={()=>run({action:'ik',nodeId,endBone:bone,target:vector,chainLength:2,maxAngle:120})}>Solve IK to local target</button>
      <details><summary>Named bone limits & mirroring</summary><p>Limits clamp local rotations during posing, playback and export. X-axis mirroring copies the selected bone to its named partner.</p><button onClick={()=>{const selected=bones.find(b=>b.name===bone);setMinimum(selected?.rotationLimits?.min??[-180,-180,-180]);setMaximum(selected?.rotationLimits?.max??[180,180,180]);setMirrorBone(selected?.mirrorBone??'');}}>Load selected bone limits</button>{([['Minimum',minimum,setMinimum],['Maximum',maximum,setMaximum]] as const).map(([label,values,setValues])=><fieldset key={label}><legend>{label} XYZ (degrees)</legend>{values.map((value,i)=><input key={i} aria-label={`${label} rotation ${'XYZ'[i]}`} type="number" value={value} onChange={e=>setValues(values.map((v,j)=>i===j?+e.target.value:v) as [number,number,number])}/>)}</fieldset>)}<label>Mirror partner<select value={mirrorBone} onChange={e=>setMirrorBone(e.target.value)}><option value="">Use named Left / Right partner</option>{bones.filter(b=>b.name!==bone).map(b=><option key={b.name}>{b.name}</option>)}</select></label><button disabled={!bones.length} onClick={()=>run({action:'joint-limits',nodeId,bone,min:minimum,max:maximum,...(mirrorBone?{mirrorBone}:{})})}>Save bone limits</button><button disabled={!bones.length} onClick={()=>run({action:'mirror-pose',nodeId,bone})}>Mirror selected pose</button></details>
    </details><details><summary>Motion & expression</summary>{node&&<SceneClipEditor key={node.id} node={rigOwner(node,doc)} run={run} onRest={()=>onJoint(-1,'rest')} onResume={()=>onTool(null)}/>}<label>Cycle duration (seconds)<input type="number" min={.2} max={30} step={.1} value={duration} onChange={e=>setDuration(+e.target.value)}/></label><label>Motion strength<input type="number" min={0} max={2} step={.1} value={strength} onChange={e=>setStrength(+e.target.value)}/></label><label>Wrist lag (fraction of wing cycle)<input type="number" min={0} max={.5} step={.01} value={wristLag} onChange={e=>setWristLag(+e.target.value)}/></label>{(['idle','wag','walk','wing-flap','roar'] as const).map(preset=><button key={preset} onClick={()=>run({action:'clip',nodeId,preset,start:doc.timeline?.duration??0,duration,strength,wristLag})}>Add {preset} clip</button>)}<label>Expression name<input value={name} onChange={e=>setName(e.target.value)}/></label><p>Select vertices in Mesh / UV / Rig; XYZ above supplies their displacement.</p><button disabled={!selection.length} onClick={()=>run({action:'morph',nodeId,name,vertices:selection,delta:vector,weight:1})}>Create expression from selection</button></details>
    <details><summary>UV & texture paint</summary><button onClick={()=>run({action:'uv-pack',nodeId,seams:[]})}>Pack triangle UV islands</button><button disabled={selection.length!==2} onClick={()=>run({action:'uv-pack',nodeId,seams:[[selection[0],selection[1]]]})}>Use selected edge as seam</button><label>Paint color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Brush radius<input type="range" min={.005} max={.4} step={.005} value={radius} onChange={e=>setRadius(+e.target.value)}/></label><svg aria-label="Paint UV texture" role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run({action:'paint',nodeId,uv:[.5,.5],radius,color});}}} viewBox="0 0 256 256" style={{background:node?.scene?.material?.color??'#ffffff',width:'100%',touchAction:'none'}} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();run({action:'paint',nodeId,uv:[(e.clientX-r.left)/r.width,1-(e.clientY-r.top)/r.height],radius,color});}}>{node?.scene?.material?.paint?.map((s,i)=><circle key={i} cx={s.uv[0]*256} cy={(1-s.uv[1])*256} r={s.radius*256} fill={s.color}/>)}</svg></details></>}
    {node&&<SceneTextureEditor key={`texture-${node.id}`} node={node} selection={selection} run={run}/>}
    {node&&<SceneAdvancedTools key={`advanced-${node.id}`} doc={doc} pageId={pageId} node={node} selection={selection} run={run} onTool={onTool} onJoint={onJoint} onIssue={onIssue}/>}<button onClick={check}>Inspect mesh & rig</button>{pending&&<button onClick={()=>{if(base!==doc){setError('Design changed. Preview again before applying.');setPending(null);return;}onDocument(pending);setPending(null);setReport('Remesh applied. Source primitives remain hidden.');}}>Apply previewed remesh</button>}{report&&<pre role="status" style={{whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{report}</pre>}{error&&<p role="alert">{error}</p>}
  </section>;
}
