import {useMemo,useState} from 'react';
import {Vector3} from 'three';
import type {DesignNode} from '../shared/schema';
import type {SceneCommand} from '../shared/scene-authoring-schema';
export function SceneTextureEditor({node,selection,run}:{node:DesignNode;selection:number[];run:(c:SceneCommand)=>void}){
 const [seams,setSeams]=useState<[number,number][]>([]),[layer,setLayer]=useState(''),[name,setName]=useState('Base color'),[map,setMap]=useState<'color'|'normal'|'roughness'>('color'),[opacity,setOpacity]=useState(1),[color,setColor]=useState('#d89b55'),[radius,setRadius]=useState(.05),[resolution,setResolution]=useState<256|512|1024|2048>(512),[distortion,setDistortion]=useState(false);
 const mesh=node.scene?.mesh,layers=node.scene?.material?.layers??[];
 const triangles=useMemo(()=>{if(!mesh?.uv)return [];const entries=[];let area3=0,area2=0;for(let i=0;i<mesh.indices.length;i+=3){const ids=mesh.indices.slice(i,i+3),p=ids.map(id=>new Vector3().fromArray(mesh.positions,id*3)),uv=ids.map(id=>mesh.uv!.slice(id*2,id*2+2));const a=p[1].sub(p[0]).cross(p[2].sub(p[0])).length()/2,b=Math.abs((uv[1][0]-uv[0][0])*(uv[2][1]-uv[0][1])-(uv[2][0]-uv[0][0])*(uv[1][1]-uv[0][1]))/2;area3+=a;area2+=b;entries.push({a,b,points:uv.map(([u,v])=>`${u*256},${(1-v)*256}`).join(' ')});}return entries.map(t=>({...t,stretch:Math.abs(Math.log2(Math.max(1e-10,t.b/Math.max(1e-10,t.a)*area3/Math.max(1e-10,area2))))}));},[mesh]);
 const paint=(uv:[number,number])=>run({action:'paint',nodeId:node.id,layerId:layer,uv,radius,color});
 return <details><summary>UV seams & material layers</summary><button disabled={selection.length!==2} onClick={()=>setSeams([...seams,[selection[0],selection[1]]])}>Add selected seam edge</button><button onClick={()=>setSeams([])}>Clear seams ({seams.length})</button><button onClick={()=>run({action:'uv-pack',nodeId:node.id,seams})}>Unwrap seam islands</button><button onClick={()=>run({action:'clear-paint',nodeId:node.id})}>Clear all paint (Undo available)</button><p>UV changes require clearing existing paint. Checker shows layout; red indicates area distortion, not an overlap certificate.</p><label><input type="checkbox" checked={distortion} onChange={e=>setDistortion(e.target.checked)}/>Show UV distortion</label>
 <label>Layer<select value={layer} onChange={e=>{setLayer(e.target.value);const l=layers.find(l=>l.id===e.target.value);if(l){setName(l.name);setMap(l.map);setOpacity(l.opacity);}}}><option value="">New layer</option>{layers.map(l=><option key={l.id} value={l.id}>{l.name} ({l.map})</option>)}</select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Map<select value={map} onChange={e=>setMap(e.target.value as typeof map)}><option value="color">Base color</option><option value="normal">Normal</option><option value="roughness">Roughness</option></select></label><label>Layer opacity<input type="range" min={0} max={1} step={.05} value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label><label>Resolution<select value={resolution} onChange={e=>setResolution(+e.target.value as typeof resolution)}>{[256,512,1024,2048].map(r=><option key={r}>{r}</option>)}</select></label><button onClick={()=>{const id=layer||`layer-${Date.now()}`;run({action:'texture-layer',nodeId:node.id,id,name,map,opacity,visible:true,resolution});setLayer(id);}}>Save layer settings</button>{layers.map(l=><label key={l.id}><input type="checkbox" checked={l.visible!==false} onChange={e=>run({action:'texture-layer',nodeId:node.id,id:l.id,name:l.name,map:l.map,opacity:l.opacity,visible:e.target.checked,resolution})}/>{l.name}</label>)}<label>Brush color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>UV brush radius<input type="range" min={.005} max={.4} step={.005} value={radius} onChange={e=>setRadius(+e.target.value)}/></label><p>Normal maps use RGB tangent-space normals (neutral #8080ff); use grayscale for roughness.</p>
 <svg viewBox="0 0 256 256" style={{width:'100%',background:'repeating-conic-gradient(#ddd 0% 25%,#888 0% 50%) 0 / 32px 32px'}} role="button" tabIndex={0} aria-label="Layer UV paint" onKeyDown={e=>{if(layer&&(e.key==='Enter'||e.key===' ')){e.preventDefault();paint([.5,.5]);}}} onPointerDown={e=>{if(!layer)return;const r=e.currentTarget.getBoundingClientRect();paint([(e.clientX-r.left)/r.width,1-(e.clientY-r.top)/r.height]);}}>{layers.filter(l=>l.id===layer&&l.visible!==false).map(l=><g key={l.id} opacity={l.opacity}>{l.strokes.map((s,i)=><circle key={i} cx={s.uv[0]*256} cy={(1-s.uv[1])*256} r={s.radius*256} fill={s.color}/>)}</g>)}{triangles.slice(0,20000).map((t,i)=><polygon key={i} points={t.points} fill={distortion?`rgba(255,40,20,${Math.min(.85,t.stretch/4)})`:'none'} stroke="#222" strokeWidth={.25}/>)}</svg>
 </details>;
}
